#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Mon Jan 18 16:48:46 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1200, 800))
        self.SetTitle("frame")

        self.Notebook = wx.Notebook(self, wx.ID_ANY)

        self.Load_Existing_Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Load_Existing_Test_Tab, "Load Test")

        Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.List_Of_Tests = wx.ListBox(self.Load_Existing_Test_Tab, wx.ID_ANY, choices=["choice 1"])
        self.List_Of_Tests.SetMinSize((500, 200))
        Tab_Sizer.Add(self.List_Of_Tests, 0, 0, 0)

        self.Load_Test = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Load Test")
        Tab_Sizer.Add(self.Load_Test, 0, 0, 0)

        self.Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Test_Tab, "Test")

        Test_Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        Current_Test_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Current Test:")
        Test_Tab_Sizer.Add(Current_Test_Label, 0, 0, 0)

        Next_Step_Image = wx.StaticBitmap(self.Test_Tab, wx.ID_ANY, wx.Bitmap("C:\\Users\\USER\\Documents\\Test_Box\\AUNA_Test_Box\\Computer_App\\demo_img.png", wx.BITMAP_TYPE_ANY))
        Test_Tab_Sizer.Add(Next_Step_Image, 0, 0, 0)

        Test_Status_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Test_Tab_Sizer.Add(Test_Status_Sizer, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Status:")
        Test_Status_Sizer.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Operation:")
        Test_Status_Sizer.Add(label_3, 0, 0, 0)

        self.Next_Step_Button = wx.Button(self.Test_Tab, wx.ID_ANY, "Next Step")
        Test_Status_Sizer.Add(self.Next_Step_Button, 0, 0, 0)

        self.New_Test_Initiator_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Initiator_Tab, "New Test")

        Creator_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.New_Test_Creator = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Creator, "New Test Creator")

        self.Result_Viewer = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Result_Viewer, "Result Viewer")

        self.New_Test_Initiator_Tab.SetSizer(Creator_Sizer)

        self.Test_Tab.SetSizer(Test_Tab_Sizer)

        self.Load_Existing_Test_Tab.SetSizer(Tab_Sizer)

        self.Layout()
        # end wxGlade

# end of class MainWindow

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
