#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Tue Feb  9 17:34:52 2021
#

import wx

###########################################################################
######Include this as well in the MainWindowUI#############################
import PinList
import SerialMonitor
import TestSequence
import PinControlUI

import logging

from pathlib import Path

from PIL import Image

#Change current directory to location of python file.
#Need to do this to load in tests properly.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))


logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

###########################################################################
##################Finish Importing Logging#################################


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1200, 800))
        self.SetTitle("Aurora NA Test Software")

        self.Notebook = wx.Notebook(self, wx.ID_ANY)

        self.Load_Existing_Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Load_Existing_Test_Tab, "Load Test")

        self.Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.List_Of_Tests_Label = wx.StaticText(self.Load_Existing_Test_Tab, wx.ID_ANY, "List of Tests found at PATH")
        self.Tab_Sizer.Add(self.List_Of_Tests_Label, 0, 0, 0)

        self.List_Of_Tests = wx.ListBox(self.Load_Existing_Test_Tab, wx.ID_ANY, choices=["choice 1"])
        self.List_Of_Tests.SetMinSize((500, 200))
        self.Tab_Sizer.Add(self.List_Of_Tests, 0, 0, 0)

        self.Test_Options_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Tab_Sizer.Add(self.Test_Options_Sizer, 1, wx.EXPAND, 0)

        self.Load_Test = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Load Test")
        self.Test_Options_Sizer.Add(self.Load_Test, 0, 0, 0)

        self.Modify_Test_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Modify Test")
        self.Test_Options_Sizer.Add(self.Modify_Test_Button, 0, 0, 0)

        self.Delete_Test_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Delete Test")
        self.Test_Options_Sizer.Add(self.Delete_Test_Button, 0, 0, 0)

        self.Start_New_Test_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "New Test")
        self.Test_Options_Sizer.Add(self.Start_New_Test_Button, 0, 0, 0)

        self.Com_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Tab_Sizer.Add(self.Com_Sizer, 1, wx.EXPAND, 0)

        self.COM_Port_Label = wx.StaticText(self.Load_Existing_Test_Tab, wx.ID_ANY, "Serial Port:")
        self.Com_Sizer.Add(self.COM_Port_Label, 0, 0, 0)

        self.Port_Connect = wx.ComboBox(self.Load_Existing_Test_Tab, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.Com_Sizer.Add(self.Port_Connect, 0, 0, 0)

        self.Connect_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Connect")
        self.Com_Sizer.Add(self.Connect_Button, 0, 0, 0)

        self.Disconnect_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Disconnect")
        self.Com_Sizer.Add(self.Disconnect_Button, 0, 0, 0)

        self.Refresh_Serial_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Refresh")
        self.Com_Sizer.Add(self.Refresh_Serial_Button, 0, 0, 0)

        self.ShowPinUI_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Show Pin UI")
        self.Tab_Sizer.Add(self.ShowPinUI_Button, 0, 0, 0)

        self.Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Test_Tab, "Test")

        self.Test_Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.Current_Test_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Current Test:")
        self.Test_Tab_Sizer.Add(self.Current_Test_Label, 0, 0, 0)

        self.Next_Step_Image = wx.StaticBitmap(self.Test_Tab, wx.ID_ANY, wx.Bitmap(1000, 500))
        self.Next_Step_Image.SetMinSize((1000, 500))
        self.Test_Tab_Sizer.Add(self.Next_Step_Image, 0, 0, 0)

        self.Test_Status_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Test_Tab_Sizer.Add(self.Test_Status_Sizer, 1, wx.EXPAND, 0)

        self.Test_Status_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Status:")
        self.Test_Status_Label.SetMinSize((200, 16))
        self.Test_Status_Sizer.Add(self.Test_Status_Label, 0, 0, 0)

        self.Stage_Description_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Operation:")
        self.Stage_Description_Label.SetMinSize((200, 16))
        self.Test_Status_Sizer.Add(self.Stage_Description_Label, 0, 0, 0)

        self.Next_Step_Button = wx.Button(self.Test_Tab, wx.ID_ANY, "Next Step")
        self.Test_Status_Sizer.Add(self.Next_Step_Button, 0, 0, 0)

        self.Close_Current_Test_Button = wx.Button(self.Test_Tab, wx.ID_ANY, "Close Test")
        self.Test_Status_Sizer.Add(self.Close_Current_Test_Button, 0, 0, 0)

        self.New_Test_Initiator_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Initiator_Tab, "New Test")

        self.Creator_Sizer = wx.BoxSizer(wx.VERTICAL)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(sizer_1, 1, wx.EXPAND, 0)

        self.Test_Name_Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Test Name:", style=wx.ALIGN_RIGHT)
        self.Test_Name_Label.SetMinSize((200, 16))
        sizer_1.Add(self.Test_Name_Label, 0, wx.ALL, 5)

        self.TestNameTextbox = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "")
        self.TestNameTextbox.SetMinSize((200, 23))
        sizer_1.Add(self.TestNameTextbox, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(sizer_2, 1, wx.EXPAND, 0)

        self.New_Test_Description_Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description:", style=wx.ALIGN_RIGHT)
        self.New_Test_Description_Label.SetMinSize((200, 16))
        sizer_2.Add(self.New_Test_Description_Label, 0, wx.ALL, 3)

        self.Test_Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "")
        self.Test_Description.SetMinSize((350, 23))
        sizer_2.Add(self.Test_Description, 0, 0, 0)

        self.label_3 = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Pins Used:", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.Creator_Sizer.Add(self.label_3, 0, wx.ALL, 4)

        self.Pins_Used_Sizer = wx.GridSizer(7, 4, 0, 0)
        self.Creator_Sizer.Add(self.Pins_Used_Sizer, 2, wx.EXPAND, 0)

        self.PinX1_1_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_1_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_1Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_1 (Analog 0)")
        self.PinX1_1_Sizer.Add(self.PinX1_1Label, 0, 0, 0)

        self.PinX1_1Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_1Select.SetSelection(2)
        self.PinX1_1_Sizer.Add(self.PinX1_1Select, 0, 0, 0)

        self.PinX1_1Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_1_Sizer.Add(self.PinX1_1Description, 0, 0, 0)

        self.PinX1_2_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_2_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_2Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_2 (Analog 1)")
        self.PinX1_2_Sizer.Add(self.PinX1_2Label, 0, 0, 0)

        self.PinX1_2Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_2Select.SetSelection(2)
        self.PinX1_2_Sizer.Add(self.PinX1_2Select, 0, 0, 0)

        self.PinX1_2Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_2_Sizer.Add(self.PinX1_2Description, 0, 0, 0)

        self.PinX1_3_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_3_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_3Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_3 (Analog 2)")
        self.PinX1_3_Sizer.Add(self.PinX1_3Label, 0, 0, 0)

        self.PinX1_3Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_3Select.SetSelection(2)
        self.PinX1_3_Sizer.Add(self.PinX1_3Select, 0, 0, 0)

        self.PinX1_3Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_3_Sizer.Add(self.PinX1_3Description, 0, 0, 0)

        self.PinX1_4_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_4_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_4Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_4 (Analog 3)")
        self.PinX1_4_Sizer.Add(self.PinX1_4Label, 0, 0, 0)

        self.PinX1_4Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_4Select.SetSelection(2)
        self.PinX1_4_Sizer.Add(self.PinX1_4Select, 0, 0, 0)

        self.PinX1_4Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_4_Sizer.Add(self.PinX1_4Description, 0, 0, 0)

        self.PinX1_5_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_5_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_5Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_5 (Analog 4)")
        self.PinX1_5_Sizer.Add(self.PinX1_5Label, 0, 0, 0)

        self.PinX1_5Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_5Select.SetSelection(2)
        self.PinX1_5_Sizer.Add(self.PinX1_5Select, 0, 0, 0)

        self.PinX1_5Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_5_Sizer.Add(self.PinX1_5Description, 0, 0, 0)

        self.PinX1_6_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_6_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_6Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_6 (Analog 5)")
        self.PinX1_6_Sizer.Add(self.PinX1_6Label, 0, 0, 0)

        self.PinX1_6Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_6_Sizer.Add(self.PinX1_6Select, 0, 0, 0)

        self.PinX1_6Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_6_Sizer.Add(self.PinX1_6Description, 0, 0, 0)

        self.PinX1_7_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_7_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_7Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_7 (Analog 6)")
        self.PinX1_7_Sizer.Add(self.PinX1_7Label, 0, 0, 0)

        self.PinX1_7Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_7Select.SetSelection(2)
        self.PinX1_7_Sizer.Add(self.PinX1_7Select, 0, 0, 0)

        self.PinX1_7Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_7_Sizer.Add(self.PinX1_7Description, 0, 0, 0)

        self.PinX1_8_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_8_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_8Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_8 (Analog 7)")
        self.PinX1_8_Sizer.Add(self.PinX1_8Label, 0, 0, 0)

        self.PinX1_8Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_8Select.SetSelection(2)
        self.PinX1_8_Sizer.Add(self.PinX1_8Select, 0, 0, 0)

        self.PinX1_8Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_8_Sizer.Add(self.PinX1_8Description, 0, 0, 0)

        self.PinX1_9_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_9_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_9Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_9 (Analog 8)")
        self.PinX1_9_Sizer.Add(self.PinX1_9Label, 0, 0, 0)

        self.PinX1_9Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_9Select.SetSelection(2)
        self.PinX1_9_Sizer.Add(self.PinX1_9Select, 0, 0, 0)

        self.PinX1_9Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_9_Sizer.Add(self.PinX1_9Description, 0, 0, 0)

        self.PinX1_10_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_10_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_10Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_10 (Analog 9)")
        self.PinX1_10_Sizer.Add(self.PinX1_10Label, 0, 0, 0)

        self.PinX1_10Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_10Select.SetSelection(2)
        self.PinX1_10_Sizer.Add(self.PinX1_10Select, 0, 0, 0)

        self.PinX1_10Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_10_Sizer.Add(self.PinX1_10Description, 0, 0, 0)

        self.PinX1_11_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_11_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_11Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_11 (Analog 10)")
        self.PinX1_11_Sizer.Add(self.PinX1_11Label, 0, 0, 0)

        self.PinX1_11Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_11Select.SetSelection(2)
        self.PinX1_11_Sizer.Add(self.PinX1_11Select, 0, 0, 0)

        self.PinX1_11Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_11_Sizer.Add(self.PinX1_11Description, 0, 0, 0)

        self.PinX1_12_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_12_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_12Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_12 (Analog 11)")
        self.PinX1_12_Sizer.Add(self.PinX1_12Label, 0, 0, 0)

        self.PinX1_12Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_12Select.SetSelection(2)
        self.PinX1_12_Sizer.Add(self.PinX1_12Select, 0, 0, 0)

        self.PinX1_12Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_12_Sizer.Add(self.PinX1_12Description, 0, 0, 0)

        self.PinX1_13_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_13_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_13Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_13 (PWM 2)")
        self.PinX1_13_Sizer.Add(self.PinX1_13Label, 0, 0, 0)

        self.PinX1_13Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_13Select.SetSelection(1)
        self.PinX1_13_Sizer.Add(self.PinX1_13Select, 0, 0, 0)

        self.PinX1_13Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_13_Sizer.Add(self.PinX1_13Description, 0, 0, 0)

        self.PinX1_14_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_14_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_14Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_14 (PWM 3)")
        self.PinX1_14_Sizer.Add(self.PinX1_14Label, 0, 0, 0)

        self.PinX1_14Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_14Select.SetSelection(1)
        self.PinX1_14_Sizer.Add(self.PinX1_14Select, 0, 0, 0)

        self.PinX1_14Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_14_Sizer.Add(self.PinX1_14Description, 0, 0, 0)

        self.PinX1_15_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_15_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_15Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_15 (PWM 4)")
        self.PinX1_15_Sizer.Add(self.PinX1_15Label, 0, 0, 0)

        self.PinX1_15Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_15Select.SetSelection(1)
        self.PinX1_15_Sizer.Add(self.PinX1_15Select, 0, 0, 0)

        self.PinX1_15Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_15_Sizer.Add(self.PinX1_15Description, 0, 0, 0)

        self.PinX1_16_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_16_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_16Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_16 (PWM 5)")
        self.PinX1_16_Sizer.Add(self.PinX1_16Label, 0, 0, 0)

        self.PinX1_16Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_16Select.SetSelection(1)
        self.PinX1_16_Sizer.Add(self.PinX1_16Select, 0, 0, 0)

        self.PinX1_16Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_16_Sizer.Add(self.PinX1_16Description, 0, 0, 0)

        self.PinX1_17_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_17_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_17Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_17 (PWM 6)")
        self.PinX1_17_Sizer.Add(self.PinX1_17Label, 0, 0, 0)

        self.PinX1_17Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_17Select.SetSelection(1)
        self.PinX1_17_Sizer.Add(self.PinX1_17Select, 0, 0, 0)

        self.PinX1_17Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_17_Sizer.Add(self.PinX1_17Description, 0, 0, 0)

        self.PinX2_1_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_1_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_1Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_1 (K1 - 12V)")
        self.PinX2_1_Sizer.Add(self.PinX2_1Label, 0, 0, 0)

        self.PinX2_1Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_1Select.SetSelection(1)
        self.PinX2_1_Sizer.Add(self.PinX2_1Select, 0, 0, 0)

        self.PinX2_1Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_1_Sizer.Add(self.PinX2_1Description, 0, 0, 0)

        self.PinX2_2_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_2_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_2Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_2 (K2 - 12V)")
        self.PinX2_2_Sizer.Add(self.PinX2_2Label, 0, 0, 0)

        self.PinX2_2Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_2Select.SetSelection(1)
        self.PinX2_2_Sizer.Add(self.PinX2_2Select, 0, 0, 0)

        self.PinX2_2Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_2_Sizer.Add(self.PinX2_2Description, 0, 0, 0)

        self.PinX2_3_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_3_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_3Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_3 (K3 - 12V)")
        self.PinX2_3_Sizer.Add(self.PinX2_3Label, 0, 0, 0)

        self.PinX2_3Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_3Select.SetSelection(1)
        self.PinX2_3_Sizer.Add(self.PinX2_3Select, 0, 0, 0)

        self.PinX2_3Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_3_Sizer.Add(self.PinX2_3Description, 0, 0, 0)

        self.PinX2_4_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_4_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_4Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_4 (K4 - 12V)")
        self.PinX2_4_Sizer.Add(self.PinX2_4Label, 0, 0, 0)

        self.PinX2_4Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_4Select.SetSelection(1)
        self.PinX2_4_Sizer.Add(self.PinX2_4Select, 0, 0, 0)

        self.PinX2_4Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_4_Sizer.Add(self.PinX2_4Description, 0, 0, 0)

        self.PinX2_5_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_5_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_5Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_5 (K5 - 24V)")
        self.PinX2_5_Sizer.Add(self.PinX2_5Label, 0, 0, 0)

        self.PinX2_5Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_5Select.SetSelection(1)
        self.PinX2_5_Sizer.Add(self.PinX2_5Select, 0, 0, 0)

        self.PinX2_5Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_5_Sizer.Add(self.PinX2_5Description, 0, 0, 0)

        self.PinX2_6_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_6_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_6Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_6 (K6 - 24V)")
        self.PinX2_6_Sizer.Add(self.PinX2_6Label, 0, 0, 0)

        self.PinX2_6Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_6Select.SetSelection(1)
        self.PinX2_6_Sizer.Add(self.PinX2_6Select, 0, 0, 0)

        self.PinX2_6Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_6_Sizer.Add(self.PinX2_6Description, 0, 0, 0)

        self.PinX2_7_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_7_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_7Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_7 (K7 - 24V)")
        self.PinX2_7_Sizer.Add(self.PinX2_7Label, 0, 0, 0)

        self.PinX2_7Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_7Select.SetSelection(1)
        self.PinX2_7_Sizer.Add(self.PinX2_7Select, 0, 0, 0)

        self.PinX2_7Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_7_Sizer.Add(self.PinX2_7Description, 0, 0, 0)

        self.PinX2_8_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_8_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_8Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_8 (K8 - 24V)")
        self.PinX2_8_Sizer.Add(self.PinX2_8Label, 0, 0, 0)

        self.PinX2_8Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_8Select.SetSelection(1)
        self.PinX2_8_Sizer.Add(self.PinX2_8Select, 0, 0, 0)

        self.PinX2_8Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_8_Sizer.Add(self.PinX2_8Description, 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.newTestButtonsSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(self.newTestButtonsSizer, 1, wx.EXPAND, 0)

        self.createNewTestButton = wx.Button(self.New_Test_Initiator_Tab, wx.ID_ANY, "Create New Test")
        self.createNewTestButton.SetMinSize((100, 40))
        self.newTestButtonsSizer.Add(self.createNewTestButton, 0, wx.ALL, 8)

        self.clearNewTestValuesButton = wx.Button(self.New_Test_Initiator_Tab, wx.ID_ANY, "Clear All Values")
        self.clearNewTestValuesButton.SetMinSize((100, 40))
        self.newTestButtonsSizer.Add(self.clearNewTestValuesButton, 0, wx.ALL, 8)

        self.New_Test_Creator = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Creator, "New Test Creator")

        self.NewTestCreatorSizer = wx.BoxSizer(wx.VERTICAL)

        self.TestInfoSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.NewTestCreatorSizer.Add(self.TestInfoSizer, 0, 0, 0)

        self.NewTestCreatorTestName = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Test Name:")
        self.NewTestCreatorTestName.SetMinSize((200, 16))
        self.TestInfoSizer.Add(self.NewTestCreatorTestName, 0, wx.ALL, 4)

        self.NewTestCreatorStageNumber = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Stage: 0/0")
        self.NewTestCreatorStageNumber.SetMinSize((200, 16))
        self.TestInfoSizer.Add(self.NewTestCreatorStageNumber, 0, wx.ALL, 4)

        self.NewTestCreatorDescriptionLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Description:")
        self.TestInfoSizer.Add(self.NewTestCreatorDescriptionLabel, 0, 0, 0)

        self.NewTestCreatorDescription = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, "")
        self.NewTestCreatorDescription.SetMinSize((220, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorDescription, 0, 0, 0)

        self.NewTestCreatorPreviousStage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Previous Stage")
        self.NewTestCreatorPreviousStage.SetMinSize((110, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorPreviousStage, 1, wx.ALL, 4)

        self.NewTestCreatorNextStage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Next Stage")
        self.NewTestCreatorNextStage.SetMinSize((110, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorNextStage, 1, wx.ALL, 4)

        self.Delete_Stage_Button = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Delete Stage")
        self.TestInfoSizer.Add(self.Delete_Stage_Button, 1, wx.ALL, 4)

        self.NewTestCreatorFinishTestButton = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Finish Test")
        self.TestInfoSizer.Add(self.NewTestCreatorFinishTestButton, 1, wx.ALL, 4)

        self.TestCreatorCurrentImg = wx.StaticBitmap(self.New_Test_Creator, wx.ID_ANY, wx.NullBitmap)
        self.NewTestCreatorSizer.Add(self.TestCreatorCurrentImg, 1, 0, 0)

        self.NewTestImageInfoSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.NewTestCreatorSizer.Add(self.NewTestImageInfoSizer, 0, wx.EXPAND, 0)

        self.NewTestCreatorImageLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Image:")
        self.NewTestImageInfoSizer.Add(self.NewTestCreatorImageLabel, 0, wx.ALL, 5)

        self.NewTestCreatorSelectImage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Select Image")
        self.NewTestCreatorSelectImage.SetMinSize((120, 30))
        self.NewTestImageInfoSizer.Add(self.NewTestCreatorSelectImage, 0, wx.ALL, 5)

        self.NewTestCreatorErrorMessageLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Error:")
        self.NewTestImageInfoSizer.Add(self.NewTestCreatorErrorMessageLabel, 0, wx.ALL, 5)

        self.NewTestCreatorErrorMessage = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, "")
        self.NewTestCreatorErrorMessage.SetMinSize((600, 23))
        self.NewTestImageInfoSizer.Add(self.NewTestCreatorErrorMessage, 0, 0, 0)

        self.NewTestCurrentImgPath = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Current Img Path : ")
        self.NewTestCreatorSizer.Add(self.NewTestCurrentImgPath, 0, 0, 0)

        self.TestPinsSizer = wx.GridSizer(7, 4, 0, 0)
        self.NewTestCreatorSizer.Add(self.TestPinsSizer, 1, wx.EXPAND, 0)

#############################################################################################################################
################################To be copied over for adding in pins to test creator segment###################################

        for x in range(1,13):
            exec("self.PinX1_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX1_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX1_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X1_{}')".format(x,x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Mode_Select = wx.ComboBox(self.New_Test_Creator, wx.ID_ANY, choices=['<', '>', '='], style=wx.CB_DROPDOWN)".format(x))
            exec("self.PinX1_{}_Stage_Mode_Select.SetSelection(-1)".format(x))
            exec("self.PinX1_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Mode_Select, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Value = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, '0')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Value, 0, 0, 0)".format(x,x))

        for x in range(13, 18):
            exec("self.PinX1_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX1_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX1_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X1_{}')".format(x,x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Value = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, '0')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Value, 0, 0, 0)".format(x,x))

        for x in range(1,9):
            exec("self.PinX2_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX2_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX2_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X2_{}')".format(x,x))
            exec("self.PinX2_{}_Stage_Sizer.Add(self.PinX2_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX2_{}_Stage_Mode_Select = wx.ComboBox(self.New_Test_Creator, wx.ID_ANY, choices=['Off','On'], style=wx.CB_DROPDOWN)".format(x))
            exec("self.PinX2_{}_Stage_Mode_Select.SetSelection(-1)".format(x))
            exec("self.PinX2_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX2_{}_Stage_Sizer.Add(self.PinX2_{}_Stage_Mode_Select, 0, 0, 0)".format(x,x))

###############################################################################################################################

        self.Result_Viewer = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Result_Viewer, "Result Viewer")

        self.New_Test_Creator.SetSizer(self.NewTestCreatorSizer)

        self.New_Test_Initiator_Tab.SetSizer(self.Creator_Sizer)

        self.Test_Tab.SetSizer(self.Test_Tab_Sizer)

        self.Load_Existing_Test_Tab.SetSizer(self.Tab_Sizer)

        self.Layout()
        # end wxGlade

# end of class MainWindow

#### To be placed under init of MainWindowUI ############################################################################################################
##########################################################################################################################################################
        
        logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

        #Modes - 0 = nothing active
        # 1 - active test being tested
        # 2 - new test being created.
        # 3 - modifying old test.
        self.current_mode = 0


        self.PinControl = PinControlUI.Pin_Control(None, wx.ID_ANY, "")
        
        #Load up ports combo box.
        preferred_index = -1
        self.Port_Connect.Clear()
        for n, (portname, desc, hwid) in enumerate(sorted(PinControlUI.SerialComm.serial.tools.list_ports.comports())):
            self.Port_Connect.Append(u'{} - {}'.format(portname, desc))
            
        self.Port_Connect.SetSelection(preferred_index)
        self.__attach_events()
        self.loadTests()

        self.test = None #Currently loaded test
        self.currentStage = None #Currently loaded stage.
        

    def __attach_events(self):

        self.Connect_Button.Bind(wx.EVT_BUTTON, self.ConnectPort)
        self.Disconnect_Button.Bind(wx.EVT_BUTTON, self.DisconnectSerialPushed)
        self.ShowPinUI_Button.Bind(wx.EVT_BUTTON, self.showPinUI)
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Load_Test.Bind(wx.EVT_BUTTON, self.LoadTestPushed)
        self.Next_Step_Button.Bind(wx.EVT_BUTTON, self.nextStepPushed)
        self.createNewTestButton.Bind(wx.EVT_BUTTON, self.onCreateNewTest)
        self.Notebook.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.onNotebookPageChange)
        self.clearNewTestValuesButton.Bind(wx.EVT_BUTTON, self.onClearAllValues)
        self.NewTestCreatorPreviousStage.Bind(wx.EVT_BUTTON, self.onNewTestPreviousStage)
        self.NewTestCreatorNextStage.Bind(wx.EVT_BUTTON, self.onNewTestNextStage)
        self.NewTestCreatorFinishTestButton.Bind(wx.EVT_BUTTON, self.onNewTestFinishTest)
        self.NewTestCreatorSelectImage.Bind(wx.EVT_BUTTON, self.onNewTestSelectImage)
        self.Modify_Test_Button.Bind(wx.EVT_BUTTON, self.modifyTestPushed)
        self.Delete_Test_Button.Bind(wx.EVT_BUTTON, self.DeleteTestPushed)
        self.Start_New_Test_Button.Bind(wx.EVT_BUTTON, self.NewTestPushed)
        self.Close_Current_Test_Button.Bind(wx.EVT_BUTTON, self.CloseTestPushed)
        self.Delete_Stage_Button.Bind(wx.EVT_BUTTON, self.onNewTestDeleteStage)
        self.Refresh_Serial_Button.Bind(wx.EVT_BUTTON, self.ReloadSerialPorts)
        #self.PortConnect()

    #loadTests - load in the test procedures located in test folder.
    #Then populate the list with them.
    def loadTests(self):
        self.List_Of_Tests.Clear()
        p = Path('.') #Using pathlib - replacement of os.
        p2 = p / "Tests"
        if p2.exists():
            self.List_Of_Tests_Label.SetLabelText("List of tests found at {}".format(p2.resolve()))
            for x in p2.iterdir():
                if x.is_dir():
                    self.List_Of_Tests.Append(x.name)
        else:
            print("error - Tests directory not found.")            

    def ConnectPort(self, events):
        self.PinControl.ExternalStartSerial(self.Port_Connect.GetSelection())
        self.Connect_Button.Enable(False)
        #Disable the connect button.
    
    def DisconnectSerialPushed(self, events):
        self.PinControl.ExternalStopSerial()
        self.Connect_Button.Enable(True)

    def showPinUI(self, events):
        self.PinControl.Show()
        #TODO: Change the PinControlUI to be able to be 'closed', made
        #not visible anymore and then able to be made visible again.

    def OnClose(self, event):
        if self.current_mode!=0:
            if wx.MessageBox("File has not been saved, continue closing?", "Please confirm below.", wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
                event.veto()
                return

        if self.current_mode==2:
            if wx.MessageBox("Test not finished being created, abort and delete progress?", "Please choose below.", wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
                event.veto()
                return
            else:
                #Remove the folder that was created and everything inside it.
                for x in self.folderPath.iterdir():
                    x.unlink()
                self.folderPath.rmdir()
                
        if self.current_mode==3:
            if wx.MessageBox("Test not finished being modified, abort and write current progress?", "Please choose below.", wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
                event.veto()
                return
            else:
                #Save the changes in a json file.
                self.saveTest()

            
        #self.PinControl.stopUIThread()
        self.PinControl.closeSelf()
        self.Destroy()
        exit(0)

    #Load in the files for the test sequence after button click.
    def loadTestSequence(self, path):
        #Get a list of all files within the test folder
        if path.exists():
            logging.info("path exists")
            for x in path.iterdir():
                if x.is_file():
                    #logging.debug("x is file")
                    if x.suffix == '.txt':
                        #logging.debug("txt file found.")
                        self.test = TestSequence.TestSequence()
                        self.test.initialLoadIn(self.PinControl.SerialLine.PinsList, x)
                    if x.suffix == '.png' or x.suffix == '.jpg' or x.suffix == '.bmp':
                        #If the suffix is an image,
                        pass
        else:
            print("Error  - file not found/path does not exist.")

        #Find the .txt, then parse in as json
        #Load the rest of the images, store in image container.
        #Need to make a class to contain it.

    def ReloadSerialPorts(self, event):
        preferred_index = -1
        self.Port_Connect.Clear()
        for n, (portname, desc, hwid) in enumerate(sorted(PinControlUI.SerialComm.serial.tools.list_ports.comports())):
            self.Port_Connect.Append(u'{} - {}'.format(portname, desc))
            
        self.Port_Connect.SetSelection(preferred_index)

    #Load the Test selected, or say no test selected/display test error.
    def LoadTestPushed(self, event):
        #On load of test, open the test tab.
        if (self.List_Of_Tests.GetSelection()==-1):
            wx.MessageBox("Nothing selected.  No action able to be performed", "No Selected Test",  wx.OK | wx.ICON_INFORMATION)
            return
        #Initiate loading test in new tab.
        #Switch tab
        p = Path('.')
        p = p/"Tests"/self.List_Of_Tests.GetStringSelection()
        logging.debug(p)
        self.loadTestSequence(p)
        #logging.info(self.test.exportJsonFile())
        self.current_mode = 1
        self.test.FolderPath = p
        self.Notebook.SetSelection(1)
        self.startTest()

    def modifyTestPushed(self, event):
        #Load in a test to be modified with new test creator tab.
        if (self.List_Of_Tests.GetSelection()==-1):
            wx.MessageBox("Nothing selected.  No action able to be performed", "No Selected Test",  wx.OK | wx.ICON_INFORMATION)
            return
        #Initiate loading test in new tab.
        #Switch tab
        p = Path('.')
        p = p/"Tests"/self.List_Of_Tests.GetStringSelection()

        logging.debug(p)
        self.loadTestSequence(p)
        self.current_mode = 3
        self.test.current_test = 0
        self.folderPath = Path('.') #Using pathlib - replacement of os.
        self.folderPath = self.folderPath / "Tests" /self.test.name
        self.testCreatorLoadInValues()

        #Set the active tab to tbe the test creator tab
        self.Notebook.SetSelection(3)

    def DeleteTestPushed(self, event):
        if (self.List_Of_Tests.GetSelection()==-1):
            wx.MessageBox("Nothing selected.  No action able to be performed", "No Selected Test",  wx.OK | wx.ICON_INFORMATION)
            return
        else:
            if wx.MessageBox("Are you sure you want to delete test {}?".format(self.List_Of_Tests.GetStringSelection()), "Delete test?",  wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
                event.veto()
                return
            
        #Find and delete directory and all contents.
        self.p = Path('.')
        self.p = self.p/"Tests"/self.List_Of_Tests.GetStringSelection()
        for x in self.p.iterdir():
            x.unlink()
        self.p.rmdir()
        self.loadTests()

    def NewTestPushed(self, event):
        #Move to the New Test page.
        self.Notebook.SetSelection(2)

    def nextStepPushed(self, event):
        if self.current_mode==1:
            if self.test.isNextTest():
                if self.currentStage.passPinCheck():
                    self.loadNextTestStage()
                else:
                    #Does not pass check
                    #Code this in.
                    pass
            else:
                self.finishTest()

    def CloseTestPushed(self, event):
        if wx.MessageBox("Test is not completed, close test and disregard progress?", "Please confirm below.", wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
            event.veto()
            return
        
        self.current_mode = 0
        p = None
        self.test = None
        self.Notebook.SetSelection(0) #Go back to default

    def startTest(self):
        self.Current_Test_Label.SetLabel("Current Test: {}".format(self.test.name))
        #Initialize Pins
        self.InitializePins()
        #Check if connected to Serial or not:

        self.loadNextTestStage()

    def InitializePins(self):
        self.PinControl.externalResetPins()
        for x in self.test.TestPinsList.PinList:
            self.PinControl.externalAddPin(x.getDict()['pin'], x.getDict()['mode'], x.getDict()['value'])
        #Start sending back pin status:
        
        self.PinControl.ConfigurePinIO(None)
        self.PinControl.ConfigOutputTime(None)

    def loadNextTestStage(self):
        self.currentStage = self.test.getNextTest()
        #Load in the image
        
        for x in self.test.FolderPath.iterdir():
            logging.debug("Checking for image {}".format(self.currentStage.image))
            if x.is_file():
                logging.debug(x.name)
                if x.name==self.currentStage.image:
                    logging.debug("Found image, updating.")
                    self.Next_Step_Image.SetBitmap(wx.Bitmap(str(x.resolve()), wx.BITMAP_TYPE_ANY))
        #Load in the test stage number, and adjust the status below
        self.Test_Status_Label.SetLabel("Stage {} out of {}".format(self.test.current_test, self.test.getNumStages()))
        #Change Operation to say Description.
        self.Stage_Description_Label.SetLabel("{}".format(self.currentStage.description))

    def finishTest(self):
        wx.MessageBox("Test finished - passed.", "Test Passed",  wx.OK | wx.ICON_INFORMATION)
        self.test = None
        self.folderPath = None
        self.current_mode = 0
        self.currentStage = None
        print(self.test)
        self.Notebook.SetSelection(0)


#####################Handling test creation#########################
    def onNotebookPageChange(self, event):
        if self.Notebook.GetSelection()==3:
            if not (self.current_mode==2 or self.current_mode==3):
                wx.MessageBox("No test being created or modified - please create a new test before creating stages.", "No Test Creation in Progress",  wx.OK | wx.ICON_INFORMATION)
                self.Notebook.SetSelection(2)
        elif self.Notebook.GetSelection()==1:
            if self.current_mode==0:
                wx.MessageBox("No test is selected - please select a test from List of Tests in 'Load Test' tab.", "No test selected.",  wx.OK | wx.ICON_INFORMATION)
                self.Notebook.SetSelection(0)     
        elif self.Notebook.GetSelection()==2:
            if self.current_mode==1:
                wx.MessageBox("Test is currently active - cannot create new test.  Please close current test before creating a test.", "Cannot create new test.", wx.OK | wx.ICON_INFORMATION)

        #Check to see if a new test is being created,
        #if not then move new test away.
    
    def onCreateNewTest(self, event):
        if self.current_mode==0:
            self.current_mode = 2
            #Make a new test object,
            #Store in the pins used, name and description.

            self.test = TestSequence.TestSequence()
            self.test.name = self.TestNameTextbox.GetValue()
            self.test.description = self.Test_Description.GetValue()
            self.test.current_test = 0
            self.getTestPinsList() #Load in the pins that will be used for this test

            self.test.currentImgPath = None
            #Set up the test creation tab
            self.NewTestCreatorTestName.SetLabelText("Test Name: {}".format(self.test.name))

            #Make a folder for this new test
            self.folderPath = Path('.') #Using pathlib - replacement of os.
            self.folderPath = self.folderPath / "Tests" /self.test.name
            self.folderPath.mkdir()
            self.Notebook.SetSelection(3)
        
        else:
            wx.MessageBox("Test already being created.", "Test Creation in Progress.",  wx.OK | wx.ICON_INFORMATION)
        #On create new test - create a new test object,
        #Move to NewTestCreator tab

    #getTestPinsList() -
    #On creating a new test, this goes through and finds each active pin
    #that will be used.
    #Also enables the pins in the stage creation menu.
    def getTestPinsList(self):
        for x in range(1,13):
            if eval("self.PinX1_{}Select.GetSelection()".format(x))==0:
                exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(x+53, x, x))
                exec("self.PinX1_{}_Stage_Mode_Select.Enable(True)".format(x))
                exec("self.PinX1_{}_Stage_Value.Enable(True)".format(x))
            elif eval("self.PinX1_{}Select.GetSelection()".format(x))==1:
                exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(x+53, x, x))
                exec("self.PinX1_{}_Stage_Value.Enable(True)".format(x))

        for x in range(13, 18):
            if eval("self.PinX1_{}Select.GetSelection()".format(x))!=1:
                exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(x-11, x, x))
                exec("self.PinX1_{}_Stage_Value.Enable(True)".format(x))

        for z in range(1,9):
            if eval("self.PinX2_{}Select.GetSelection()".format(z))!=1:
                exec("self.test.TestPinsList.addPin({}, self.PinX2_{}Select.GetSelection(), 0, self.PinX2_{}Description.GetValue())".format(z+21, z, z))
                exec("self.PinX2_{}_Stage_Mode_Select.Enable(True)".format(z))

    def onClearAllValues(self, event):
        #All the values are reset for the new test creator tab
        for x in range(1,14):
            exec("self.PinX1_{}Select.SetSelection(2)".format(x))
            exec("self.PinX1_{}Description.SetValue('Description')".format(x))
            if x!=13:
                exec("self.PinX1_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
        for x in range(14, 18):
            exec("self.PinX1_{}Select.SetSelection(1)".format(x))
            exec("self.PinX1_{}Description.SetValue('Description')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))

        for z in range(1,9):
            exec("self.PinX2_{}Select.SetSelection(1)".format(z))
            exec("self.PinX2_{}Description.SetValue('Description')".format(z))
            exec("self.PinX2_{}_Stage_Mode_Select.Enable(False)".format(z))

    #onNewTestStage() - when the new test next stage button is clicked.
    def onNewTestNextStage(self, event):
        #Make sure all necessary values actually exist
        #Check for existing img path, and write image to folder.
        if not self.test.currentImgPath:
            wx.MessageBox("No image selected, please select an image", "No image selected",  wx.OK | wx.ICON_INFORMATION)
            return 0
        #Check for pins actually having values.

        #Store all the values into the test stage object
        #Change this storage up to use the currentStage class??

        #Save Stage - depending on if we are in the last stage or a previous stage, save differently.
        if self.test.current_test==(len(self.test.testStages)): #Append a new stage
            self.test.testStages.append(TestSequence.testStage(self.test.current_test, self.NewTestCreatorDescription.GetValue(), "img{}.png".format(self.test.current_test), self.getNewTestCreatorPins(), self.NewTestCreatorErrorMessage.GetValue(), None))
            self.test.current_test+=1
            #Clear currentImgPath
            self.test.currentImgPath = None
            self.updateNewTestCreatorNumber()
            self.drawNewTestImage()
        else: #Save current stage, load old stage.
            self.test.testStages[self.test.current_test] = TestSequence.testStage(self.test.current_test, self.NewTestCreatorDescription.GetValue(), "img{}.png".format(self.test.current_test), self.getNewTestCreatorPins(), self.NewTestCreatorErrorMessage.GetValue(), None)
            #Also, load in the next test status.
            self.test.current_test+=1
            self.testCreatorLoadInValues()
            self.drawNewTestImage()

        #Increment stage levels
        print("Test stage {} saved.".format(self.test.current_test-1))
        print(self.test.exportJsonFile())

    def onNewTestDeleteStage(self, event):
        #Delete stage
        #Increment backwards.
        self.onNewTestPreviousStage(None)
        self.test.testStages.pop(self.test.current_test+1)
        self.updateNewTestCreatorNumber()
        self.testCreatorLoadInValues()
        self.drawNewTestImage()

    #Return a dict with all pins and values.
    def getNewTestCreatorPins(self):
        returnDict = []
        for x in range(1,14):
            if eval("self.PinX1_{}_Stage_Value.IsEnabled()".format(x)):
                if eval("self.PinX1_{}_Stage_Value.GetValue()==''".format(x,x)):
                    #send message that there needs to be a value in this value box before saving
                    wx.MessageBox("Please check values for pin X1_{} in order to save stage.".format(x), "Check values",  wx.OK | wx.ICON_INFORMATION)
                else:
                    returnDict.append(self.getPinObject("X1_{}".format(x)))
        for x in range(14, 18):
            if eval("self.PinX1_{}_Stage_Value.IsEnabled()".format(x)):
                if eval("self.PinX1_{}_Stage_Value.GetValue()==''".format(x)):
                    #send message that there needs to be a value in this value box before saving
                    wx.MessageBox("Please check values for pin X1_{} in order to save stage.".format(x), "Check values",  wx.OK | wx.ICON_INFORMATION)
                else:
                    returnDict.append(self.getPinObject("X1_{}".format(x)))

        for x in range(1, 9):
            if eval("self.PinX2_{}_Stage_Mode_Select.IsEnabled()".format(x)):
                if eval("self.PinX2_{}_Stage_Mode_Select.GetValue()==''".format(x)):
                    wx.MessageBox("Please check values for pin X2_{} in order to save stage.".format(x), "Check values",  wx.OK | wx.ICON_INFORMATION)
                else:
                    returnDict.append(self.getPinObject("X2_{}".format(x)))
        
        
        print("getNewTestCreatorPinsReturn:")
        for z in returnDict:
           print(z.getDict())

        return returnDict

    def getPinObject(self, PinID):
        ret = TestSequence.testPin(0,0,0,None)
        ret.pin = self.translateConnectorToPin(PinID)
        if ret.pin<53:
            pass
        else:
            ret.check_code = eval("self.Pin{}_Stage_Mode_Select.GetSelection()".format(PinID))
        if not PinID.split("_")[0]=="X2":
            ret.value = eval("self.Pin{}_Stage_Value.GetValue()".format(PinID))

        return ret

    def translateConnectorToPin(self, PinID):
        if int(PinID[1])==1:
            if int(PinID.split("_")[1])<13:
                return int(PinID.split("_")[1])+53
            else:
                return int(PinID.split("_")[1])-11
        else:
            return int(PinID.split("_")[1])+21

    def translatePinToConnector(self, PinNumber):
        if PinNumber>53:
            return "X1_{}".format(PinNumber-53)
        elif PinNumber>21:
            return "X2_{}".format(PinNumber-21)
        return "X1_{}".format(PinNumber+11)
        
    def setNewTestCreatorPinVal(self, pin): #Used in navigating backwards in pin system.
        
        #Check to see if this stage value should be set - make sure it's not an X2 first.
        if not (pin['pin']>21 and pin['pin']<30):
            exec("self.Pin{}_Stage_Value.SetValue(\"{}\")".format(str(self.translatePinToConnector(pin['pin'])), str(pin['value'])))
        
        #Finish this check here - make sure this pin is within required values.
        if pin['pin']>21:
            print("Pin {} is {}".format(pin['pin'], self.translatePinToConnector(pin['pin'])))
            exec("self.Pin{}_Stage_Mode_Select.SetSelection({})".format(str(self.translatePinToConnector(pin['pin'])), str(pin['check_code'])))
            print("Pin {} set to code {}".format(self.translatePinToConnector(pin['pin']), pin['check_code']))
        
        print("Pin {} set to {}".format(str(self.translatePinToConnector(pin['pin'])), str(pin['value'])))
        
    def onNewTestPreviousStage(self, event):
        #First check if there is a previous stage
        if self.test.current_test==0:
            wx.MessageBox("Currently at the starting test stage, there are no previous tests to choose from.", "No Previous Tests",  wx.OK | wx.ICON_INFORMATION)
            return
        
        #If not, save current test stage:
        #if self.test.current_test>(len(self.test.testStages)-1):
            #self.test.testStages.append(TestSequence.testStage(self.test.current_test, self.NewTestCreatorDescription.GetValue(), self.test.currentImgPath, self.getNewTestCreatorPins(), self.NewTestCreatorErrorMessage.GetValue(), None))
        #else:
        #self.test.testStages[self.test.current_test] = TestSequence.testStage(self.test.current_test, self.NewTestCreatorDescription.GetValue(), self.test.currentImgPath, self.getNewTestCreatorPins(), self.NewTestCreatorErrorMessage.GetValue(), None)
        
        self.test.current_test-=1
        #self.test.testStages[self.test.current_test]
        self.testCreatorLoadInValues();

       
        print("Navigated backwards.")

    def enableModifyTestPins(self):
        for z in self.test.TestPinsList.PinList:
            if z.pin>53:
                if z.mode==0: #Input
                    exec("self.Pin{}_Stage_Mode_Select.Enable(True)".format(self.translatePinToConnector(z.pin)))
                    exec("self.Pin{}_Stage_Value.Enable(True)".format(self.translatePinToConnector(z.pin)))
                else:
                    exec("self.Pin{}_Stage_Value.Enable(True)".format(self.translatePinToConnector(z.pin)))
            elif z.pin<7:
                exec("self.Pin{}_Stage_Value.Enable(True)".format(self.translatePinToConnector(z.pin)))
            elif z.pin<30:
                exec("self.Pin{}_Stage_Mode_Select.Enable(True)".format(self.translatePinToConnector(z.pin)))

    def testCreatorLoadInValues(self):
         #Load in the previous test values:
        #Number:
        self.updateNewTestCreatorNumber()
        #Description
        self.NewTestCreatorDescription.SetValue(self.test.testStages[self.test.current_test].getDict()['description'])
        #Error
        self.NewTestCreatorErrorMessage.SetValue(self.test.testStages[self.test.current_test].getDict()['error'])
        #Image path
        self.test.currentImgPath = self.test.testStages[self.test.current_test].getDict()['image']
        #All pins and their values

        #Enable the pins that are used for this test:
        self.enableModifyTestPins()

        for z in self.test.testStages[self.test.current_test].getDict()['pin_check']:
            self.setNewTestCreatorPinVal(z)
        
        #Update the image on screen:
        self.drawNewTestImage()

        print("Finished loading in previously-made test creator stage {}.".format(self.test.current_test))
        print(self.test.testStages[self.test.current_test].getDict())

    def updateNewTestCreatorNumber(self):
        self.NewTestCreatorStageNumber.SetLabelText("Stage: {}/{}".format(self.test.current_test, len(self.test.testStages)))

    def onNewTestFinishTest(self, event):
        #Save the test
        #Dump the JSON file:
        self.saveTest()
        #Reset the variables associated with a new test
        self.test = None
        self.folderPath = None
        self.current_mode = 0
        self.currentStage = None

        self.loadTests()
        self.Notebook.SetSelection(0)

    def saveTest(self):
        with open("{}/{}.txt".format(self.folderPath, self.test.name), 'w') as outfile:
            outfile.write(self.test.exportJsonFile())
            outfile.close()
        
    def onResultViewer(self, event):
        #
        pass

    def onNewTestSelectImage(self, event):
        #Open a box to select the image for a certain stage.
        with wx.FileDialog(self, "Open Image", wildcard = "Image files (*.png;*.gif;*.jpeg;*.jpg)|*.png;*.gif;*.jpeg;*.jpg",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as fileDialog:
            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return
            pathname = fileDialog.GetPath()
            self.test.currentImgPath = pathname
            img = Image.open(self.test.currentImgPath)
            img.save("{}\img{}.png".format(self.folderPath.resolve(),self.test.current_test))
        #Also draw image to screen:
        self.drawNewTestImage()

    def drawNewTestImage(self):
        for x in self.folderPath.iterdir():
            logging.debug("Checking for image {}".format("img{}.png".format(self.test.current_test)))
            if x.is_file():
                logging.debug(x.name)
                if x.name=="img{}.png".format(self.test.current_test):
                    logging.debug("Found image, updating.")
                    self.TestCreatorCurrentImg.SetBitmap(wx.Bitmap(str(x.resolve()), wx.BITMAP_TYPE_ANY))
                    self.NewTestCurrentImgPath.SetLabelText("Current Image Path: "+str(x.resolve()))
                    return 0            
        self.NewTestCurrentImgPath.SetLabelText("Current Image Path: None")
        self.TestCreatorCurrentImg.ClearBackground()


###############################################################################################################################################

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
