#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Tue Feb  9 17:34:52 2021
#

import wx

###########################################################################
######Include this as well in the MainWindowUI#############################
import PinList
import SerialMonitor
import TestSequence
import PinControlUI

import logging

from pathlib import Path

#Change current directory to location of python file.
#Need to do this to load in tests properly.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))


###########################################################################
##################Finish Importing Logging#################################


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1200, 800))
        self.SetTitle("frame")

        self.Notebook = wx.Notebook(self, wx.ID_ANY)

        self.Load_Existing_Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Load_Existing_Test_Tab, "Load Test")

        self.Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.List_Of_Tests = wx.ListBox(self.Load_Existing_Test_Tab, wx.ID_ANY, choices=["choice 1"])
        self.List_Of_Tests.SetMinSize((500, 200))
        self.Tab_Sizer.Add(self.List_Of_Tests, 0, 0, 0)

        self.Load_Test = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Load Test")
        self.Tab_Sizer.Add(self.Load_Test, 0, 0, 0)

        self.Com_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Tab_Sizer.Add(self.Com_Sizer, 1, wx.EXPAND, 0)

        self.COM_Port_Label = wx.StaticText(self.Load_Existing_Test_Tab, wx.ID_ANY, "Serial Port:")
        self.Com_Sizer.Add(self.COM_Port_Label, 0, 0, 0)

        self.Port_Connect = wx.ComboBox(self.Load_Existing_Test_Tab, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.Com_Sizer.Add(self.Port_Connect, 0, 0, 0)

        self.Connect_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Connect")
        self.Com_Sizer.Add(self.Connect_Button, 0, 0, 0)

        self.Disconnect_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Disconnect")
        self.Com_Sizer.Add(self.Disconnect_Button, 0, 0, 0)

        self.ShowPinUI_Button = wx.Button(self.Load_Existing_Test_Tab, wx.ID_ANY, "Show Pin UI")
        self.Tab_Sizer.Add(self.ShowPinUI_Button, 0, 0, 0)

        self.Test_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Test_Tab, "Test")

        self.Test_Tab_Sizer = wx.BoxSizer(wx.VERTICAL)

        self.Current_Test_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Current Test:")
        self.Test_Tab_Sizer.Add(self.Current_Test_Label, 0, 0, 0)

        self.Next_Step_Image = wx.StaticBitmap(self.Test_Tab, wx.ID_ANY, wx.Bitmap("C:\\Users\\USER\\Documents\\Test_Box\\AUNA_Test_Box\\Computer_App\\demo_img.png", wx.BITMAP_TYPE_ANY))
        self.Next_Step_Image.SetMinSize((1000, 500))
        self.Test_Tab_Sizer.Add(self.Next_Step_Image, 0, 0, 0)

        self.Test_Status_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Test_Tab_Sizer.Add(self.Test_Status_Sizer, 1, wx.EXPAND, 0)

        self.Test_Status_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Status:")
        self.Test_Status_Label.SetMinSize((200, 16))
        self.Test_Status_Sizer.Add(self.Test_Status_Label, 0, 0, 0)

        self.Stage_Description_Label = wx.StaticText(self.Test_Tab, wx.ID_ANY, "Operation:")
        self.Stage_Description_Label.SetMinSize((200, 16))
        self.Test_Status_Sizer.Add(self.Stage_Description_Label, 0, 0, 0)

        self.Next_Step_Button = wx.Button(self.Test_Tab, wx.ID_ANY, "Next Step")
        self.Test_Status_Sizer.Add(self.Next_Step_Button, 0, 0, 0)

        self.New_Test_Initiator_Tab = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Initiator_Tab, "New Test")

        self.Creator_Sizer = wx.BoxSizer(wx.VERTICAL)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(sizer_1, 1, wx.EXPAND, 0)

        self.Test_Name_Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Test Name:", style=wx.ALIGN_RIGHT)
        self.Test_Name_Label.SetMinSize((200, 16))
        sizer_1.Add(self.Test_Name_Label, 0, wx.ALL, 5)

        self.TestNameTextbox = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "")
        self.TestNameTextbox.SetMinSize((200, 23))
        sizer_1.Add(self.TestNameTextbox, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(sizer_2, 1, wx.EXPAND, 0)

        self.New_Test_Description_Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description:", style=wx.ALIGN_RIGHT)
        self.New_Test_Description_Label.SetMinSize((200, 16))
        sizer_2.Add(self.New_Test_Description_Label, 0, wx.ALL, 3)

        self.Test_Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "")
        self.Test_Description.SetMinSize((350, 23))
        sizer_2.Add(self.Test_Description, 0, 0, 0)

        self.label_3 = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "Pins Used:", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.Creator_Sizer.Add(self.label_3, 0, wx.ALL, 4)

        self.Pins_Used_Sizer = wx.GridSizer(7, 4, 0, 0)
        self.Creator_Sizer.Add(self.Pins_Used_Sizer, 2, wx.EXPAND, 0)

        self.PinX1_1_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_1_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_1Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_1 (Analog 0)")
        self.PinX1_1_Sizer.Add(self.PinX1_1Label, 0, 0, 0)

        self.PinX1_1Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_1Select.SetSelection(2)
        self.PinX1_1_Sizer.Add(self.PinX1_1Select, 0, 0, 0)

        self.PinX1_1Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_1_Sizer.Add(self.PinX1_1Description, 0, 0, 0)

        self.PinX1_2_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_2_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_2Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_2 (Analog 1)")
        self.PinX1_2_Sizer.Add(self.PinX1_2Label, 0, 0, 0)

        self.PinX1_2Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_2Select.SetSelection(2)
        self.PinX1_2_Sizer.Add(self.PinX1_2Select, 0, 0, 0)

        self.PinX1_2Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_2_Sizer.Add(self.PinX1_2Description, 0, 0, 0)

        self.PinX1_3_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_3_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_3Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_3 (Analog 2)")
        self.PinX1_3_Sizer.Add(self.PinX1_3Label, 0, 0, 0)

        self.PinX1_3Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_3Select.SetSelection(2)
        self.PinX1_3_Sizer.Add(self.PinX1_3Select, 0, 0, 0)

        self.PinX1_3Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_3_Sizer.Add(self.PinX1_3Description, 0, 0, 0)

        self.PinX1_4_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_4_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_4Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_4 (Analog 3)")
        self.PinX1_4_Sizer.Add(self.PinX1_4Label, 0, 0, 0)

        self.PinX1_4Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_4Select.SetSelection(2)
        self.PinX1_4_Sizer.Add(self.PinX1_4Select, 0, 0, 0)

        self.PinX1_4Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_4_Sizer.Add(self.PinX1_4Description, 0, 0, 0)

        self.PinX1_5_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_5_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_5Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_5 (Analog 4)")
        self.PinX1_5_Sizer.Add(self.PinX1_5Label, 0, 0, 0)

        self.PinX1_5Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_5Select.SetSelection(2)
        self.PinX1_5_Sizer.Add(self.PinX1_5Select, 0, 0, 0)

        self.PinX1_5Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_5_Sizer.Add(self.PinX1_5Description, 0, 0, 0)

        self.PinX1_6_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_6_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_6Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_6 (Analog 5)")
        self.PinX1_6_Sizer.Add(self.PinX1_6Label, 0, 0, 0)

        self.PinX1_6Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_6_Sizer.Add(self.PinX1_6Select, 0, 0, 0)

        self.PinX1_6Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_6_Sizer.Add(self.PinX1_6Description, 0, 0, 0)

        self.PinX1_7_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_7_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_7Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_7 (Analog 6)")
        self.PinX1_7_Sizer.Add(self.PinX1_7Label, 0, 0, 0)

        self.PinX1_7Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_7Select.SetSelection(2)
        self.PinX1_7_Sizer.Add(self.PinX1_7Select, 0, 0, 0)

        self.PinX1_7Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_7_Sizer.Add(self.PinX1_7Description, 0, 0, 0)

        self.PinX1_8_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_8_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_8Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_8 (Analog 7)")
        self.PinX1_8_Sizer.Add(self.PinX1_8Label, 0, 0, 0)

        self.PinX1_8Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_8Select.SetSelection(2)
        self.PinX1_8_Sizer.Add(self.PinX1_8Select, 0, 0, 0)

        self.PinX1_8Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_8_Sizer.Add(self.PinX1_8Description, 0, 0, 0)

        self.PinX1_9_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_9_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_9Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_9 (Analog 8)")
        self.PinX1_9_Sizer.Add(self.PinX1_9Label, 0, 0, 0)

        self.PinX1_9Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_9Select.SetSelection(2)
        self.PinX1_9_Sizer.Add(self.PinX1_9Select, 0, 0, 0)

        self.PinX1_9Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_9_Sizer.Add(self.PinX1_9Description, 0, 0, 0)

        self.PinX1_10_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_10_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_10Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_10 (Analog 9)")
        self.PinX1_10_Sizer.Add(self.PinX1_10Label, 0, 0, 0)

        self.PinX1_10Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_10Select.SetSelection(2)
        self.PinX1_10_Sizer.Add(self.PinX1_10Select, 0, 0, 0)

        self.PinX1_10Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_10_Sizer.Add(self.PinX1_10Description, 0, 0, 0)

        self.PinX1_11_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_11_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_11Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_11 (Analog 10)")
        self.PinX1_11_Sizer.Add(self.PinX1_11Label, 0, 0, 0)

        self.PinX1_11Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_11Select.SetSelection(2)
        self.PinX1_11_Sizer.Add(self.PinX1_11Select, 0, 0, 0)

        self.PinX1_11Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_11_Sizer.Add(self.PinX1_11Description, 0, 0, 0)

        self.PinX1_12_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_12_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_12Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_12 (Analog 11)")
        self.PinX1_12_Sizer.Add(self.PinX1_12Label, 0, 0, 0)

        self.PinX1_12Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Input", "Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_12Select.SetSelection(2)
        self.PinX1_12_Sizer.Add(self.PinX1_12Select, 0, 0, 0)

        self.PinX1_12Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_12_Sizer.Add(self.PinX1_12Description, 0, 0, 0)

        self.PinX1_13_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_13_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_13Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_13 (PWM 2)")
        self.PinX1_13_Sizer.Add(self.PinX1_13Label, 0, 0, 0)

        self.PinX1_13Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_13Select.SetSelection(1)
        self.PinX1_13_Sizer.Add(self.PinX1_13Select, 0, 0, 0)

        self.PinX1_13Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_13_Sizer.Add(self.PinX1_13Description, 0, 0, 0)

        self.PinX1_14_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_14_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_14Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_14 (PWM 3)")
        self.PinX1_14_Sizer.Add(self.PinX1_14Label, 0, 0, 0)

        self.PinX1_14Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_14Select.SetSelection(1)
        self.PinX1_14_Sizer.Add(self.PinX1_14Select, 0, 0, 0)

        self.PinX1_14Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_14_Sizer.Add(self.PinX1_14Description, 0, 0, 0)

        self.PinX1_15_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_15_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_15Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_15 (PWM 4)")
        self.PinX1_15_Sizer.Add(self.PinX1_15Label, 0, 0, 0)

        self.PinX1_15Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_15Select.SetSelection(1)
        self.PinX1_15_Sizer.Add(self.PinX1_15Select, 0, 0, 0)

        self.PinX1_15Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_15_Sizer.Add(self.PinX1_15Description, 0, 0, 0)

        self.PinX1_16_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_16_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_16Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_16 (PWM 5)")
        self.PinX1_16_Sizer.Add(self.PinX1_16Label, 0, 0, 0)

        self.PinX1_16Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_16Select.SetSelection(1)
        self.PinX1_16_Sizer.Add(self.PinX1_16Select, 0, 0, 0)

        self.PinX1_16Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_16_Sizer.Add(self.PinX1_16Description, 0, 0, 0)

        self.PinX1_17_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX1_17_Sizer, 1, wx.EXPAND, 0)

        self.PinX1_17Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X1_17 (PWM 6)")
        self.PinX1_17_Sizer.Add(self.PinX1_17Label, 0, 0, 0)

        self.PinX1_17Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX1_17Select.SetSelection(1)
        self.PinX1_17_Sizer.Add(self.PinX1_17Select, 0, 0, 0)

        self.PinX1_17Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX1_17_Sizer.Add(self.PinX1_17Description, 0, 0, 0)

        self.PinX2_1_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_1_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_1Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_1 (K1 - 12V)")
        self.PinX2_1_Sizer.Add(self.PinX2_1Label, 0, 0, 0)

        self.PinX2_1Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_1Select.SetSelection(1)
        self.PinX2_1_Sizer.Add(self.PinX2_1Select, 0, 0, 0)

        self.PinX2_1Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_1_Sizer.Add(self.PinX2_1Description, 0, 0, 0)

        self.PinX2_2_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_2_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_2Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_2 (K2 - 12V)")
        self.PinX2_2_Sizer.Add(self.PinX2_2Label, 0, 0, 0)

        self.PinX2_2Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_2Select.SetSelection(1)
        self.PinX2_2_Sizer.Add(self.PinX2_2Select, 0, 0, 0)

        self.PinX2_2Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_2_Sizer.Add(self.PinX2_2Description, 0, 0, 0)

        self.PinX2_3_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_3_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_3Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_3 (K3 - 12V)")
        self.PinX2_3_Sizer.Add(self.PinX2_3Label, 0, 0, 0)

        self.PinX2_3Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_3Select.SetSelection(1)
        self.PinX2_3_Sizer.Add(self.PinX2_3Select, 0, 0, 0)

        self.PinX2_3Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_3_Sizer.Add(self.PinX2_3Description, 0, 0, 0)

        self.PinX2_4_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_4_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_4Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_4 (K4 - 12V)")
        self.PinX2_4_Sizer.Add(self.PinX2_4Label, 0, 0, 0)

        self.PinX2_4Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_4Select.SetSelection(1)
        self.PinX2_4_Sizer.Add(self.PinX2_4Select, 0, 0, 0)

        self.PinX2_4Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_4_Sizer.Add(self.PinX2_4Description, 0, 0, 0)

        self.PinX2_5_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_5_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_5Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_5 (K5 - 24V)")
        self.PinX2_5_Sizer.Add(self.PinX2_5Label, 0, 0, 0)

        self.PinX2_5Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_5Select.SetSelection(1)
        self.PinX2_5_Sizer.Add(self.PinX2_5Select, 0, 0, 0)

        self.PinX2_5Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_5_Sizer.Add(self.PinX2_5Description, 0, 0, 0)

        self.PinX2_6_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_6_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_6Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_6 (K6 - 24V)")
        self.PinX2_6_Sizer.Add(self.PinX2_6Label, 0, 0, 0)

        self.PinX2_6Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_6Select.SetSelection(1)
        self.PinX2_6_Sizer.Add(self.PinX2_6Select, 0, 0, 0)

        self.PinX2_6Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_6_Sizer.Add(self.PinX2_6Description, 0, 0, 0)

        self.PinX2_7_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_7_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_7Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_7 (K7 - 24V)")
        self.PinX2_7_Sizer.Add(self.PinX2_7Label, 0, 0, 0)

        self.PinX2_7Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_7Select.SetSelection(1)
        self.PinX2_7_Sizer.Add(self.PinX2_7Select, 0, 0, 0)

        self.PinX2_7Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_7_Sizer.Add(self.PinX2_7Description, 0, 0, 0)

        self.PinX2_8_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Pins_Used_Sizer.Add(self.PinX2_8_Sizer, 1, wx.EXPAND, 0)

        self.PinX2_8Label = wx.StaticText(self.New_Test_Initiator_Tab, wx.ID_ANY, "X2_8 (K8 - 24V)")
        self.PinX2_8_Sizer.Add(self.PinX2_8Label, 0, 0, 0)

        self.PinX2_8Select = wx.ComboBox(self.New_Test_Initiator_Tab, wx.ID_ANY, choices=["Output", "Unused"], style=wx.CB_DROPDOWN)
        self.PinX2_8Select.SetSelection(1)
        self.PinX2_8_Sizer.Add(self.PinX2_8Select, 0, 0, 0)

        self.PinX2_8Description = wx.TextCtrl(self.New_Test_Initiator_Tab, wx.ID_ANY, "Description")
        self.PinX2_8_Sizer.Add(self.PinX2_8Description, 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.Pins_Used_Sizer.Add((0, 0), 0, 0, 0)

        self.newTestButtonsSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.Creator_Sizer.Add(self.newTestButtonsSizer, 1, wx.EXPAND, 0)

        self.createNewTestButton = wx.Button(self.New_Test_Initiator_Tab, wx.ID_ANY, "Create New Test")
        self.createNewTestButton.SetMinSize((100, 40))
        self.newTestButtonsSizer.Add(self.createNewTestButton, 0, wx.ALL, 8)

        self.clearNewTestValuesButton = wx.Button(self.New_Test_Initiator_Tab, wx.ID_ANY, "Clear All Values")
        self.clearNewTestValuesButton.SetMinSize((100, 40))
        self.newTestButtonsSizer.Add(self.clearNewTestValuesButton, 0, wx.ALL, 8)

        self.New_Test_Creator = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.New_Test_Creator, "New Test Creator")

        self.NewTestCreatorSizer = wx.BoxSizer(wx.VERTICAL)

        self.TestInfoSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.NewTestCreatorSizer.Add(self.TestInfoSizer, 1, wx.EXPAND, 0)

        self.NewTestCreatorTestName = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Test Name:")
        self.NewTestCreatorTestName.SetMinSize((200, 16))
        self.TestInfoSizer.Add(self.NewTestCreatorTestName, 0, wx.ALL, 4)

        self.NewTestCreatorStageNumber = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Stage: 0/0")
        self.NewTestCreatorStageNumber.SetMinSize((200, 16))
        self.TestInfoSizer.Add(self.NewTestCreatorStageNumber, 0, wx.ALL, 4)

        self.NewTestCreatorDescriptionLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Description:")
        self.TestInfoSizer.Add(self.NewTestCreatorDescriptionLabel, 0, 0, 0)

        self.NewTestCreatorDescription = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, "")
        self.NewTestCreatorDescription.SetMinSize((220, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorDescription, 0, 0, 0)

        self.NewTestCreatorPreviousStage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Previous Stage")
        self.NewTestCreatorPreviousStage.SetMinSize((150, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorPreviousStage, 0, wx.ALL, 4)

        self.NewTestCreatorNextStage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Next Stage")
        self.NewTestCreatorNextStage.SetMinSize((140, 23))
        self.TestInfoSizer.Add(self.NewTestCreatorNextStage, 0, wx.ALL, 4)

        self.NewTestCreatorFinishTestButton = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Finish Test")
        self.TestInfoSizer.Add(self.NewTestCreatorFinishTestButton, 1, wx.ALL, 4)

        self.Horizontal_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.NewTestCreatorSizer.Add(self.Horizontal_Sizer, 1, wx.EXPAND, 0)

        self.NewTestCreatorImageLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Image:")
        self.Horizontal_Sizer.Add(self.NewTestCreatorImageLabel, 0, wx.ALL, 5)

        self.NewTestCreatorSelectImage = wx.Button(self.New_Test_Creator, wx.ID_ANY, "Select Image")
        self.NewTestCreatorSelectImage.SetMinSize((120, 30))
        self.Horizontal_Sizer.Add(self.NewTestCreatorSelectImage, 0, wx.ALL, 5)

        self.NewTestCreatorErrorMessageLabel = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, "Error:")
        self.Horizontal_Sizer.Add(self.NewTestCreatorErrorMessageLabel, 0, wx.ALL, 5)

        self.NewTestCreatorErrorMessage = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, "")
        self.NewTestCreatorErrorMessage.SetMinSize((600, 23))
        self.Horizontal_Sizer.Add(self.NewTestCreatorErrorMessage, 0, 0, 0)

        self.TestPinsSizer = wx.GridSizer(7, 4, 0, 0)
        self.NewTestCreatorSizer.Add(self.TestPinsSizer, 1, wx.EXPAND, 0)

#############################################################################################################################
################################To be copied over for adding in pins to test creator segment###################################

        for x in range(1,13):
            exec("self.PinX1_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX1_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX1_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X1_{}')".format(x,x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Mode_Select = wx.ComboBox(self.New_Test_Creator, wx.ID_ANY, choices=['<', '>', '='], style=wx.CB_DROPDOWN)".format(x))
            exec("self.PinX1_{}_Stage_Mode_Select.SetSelection(-1)".format(x))
            exec("self.PinX1_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Mode_Select, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Value = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, '0')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Value, 0, 0, 0)".format(x,x))

        for x in range(13, 18):
            exec("self.PinX1_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX1_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX1_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X1_{}')".format(x,x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX1_{}_Stage_Value = wx.TextCtrl(self.New_Test_Creator, wx.ID_ANY, '0')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Sizer.Add(self.PinX1_{}_Stage_Value, 0, 0, 0)".format(x,x))

        for x in range(1,9):
            exec("self.PinX2_{}_Stage_Sizer = wx.BoxSizer(wx.HORIZONTAL)".format(x))
            exec("self.TestPinsSizer.Add(self.PinX2_{}_Stage_Sizer, 1, wx.EXPAND, 0)".format(x))
            exec("self.PinX2_{}_Stage_Label = wx.StaticText(self.New_Test_Creator, wx.ID_ANY, 'X2_{}')".format(x,x))
            exec("self.PinX2_{}_Stage_Sizer.Add(self.PinX2_{}_Stage_Label, 0, 0, 0)".format(x,x))
            exec("self.PinX2_{}_Stage_Mode_Select = wx.ComboBox(self.New_Test_Creator, wx.ID_ANY, choices=['Off','On'], style=wx.CB_DROPDOWN)".format(x))
            exec("self.PinX2_{}_Stage_Mode_Select.SetSelection(-1)".format(x))
            exec("self.PinX2_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX2_{}_Stage_Sizer.Add(self.PinX2_{}_Stage_Mode_Select, 0, 0, 0)".format(x,x))

###############################################################################################################################

        self.Result_Viewer = wx.Panel(self.Notebook, wx.ID_ANY)
        self.Notebook.AddPage(self.Result_Viewer, "Result Viewer")

        self.New_Test_Creator.SetSizer(self.NewTestCreatorSizer)

        self.New_Test_Initiator_Tab.SetSizer(self.Creator_Sizer)

        self.Test_Tab.SetSizer(self.Test_Tab_Sizer)

        self.Load_Existing_Test_Tab.SetSizer(self.Tab_Sizer)

        self.Layout()
        # end wxGlade

# end of class MainWindow

#### To be placed under init of MainWindowUI ############################################################################################################
##########################################################################################################################################################
        
        logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

        self.stopClose = False
        self.testActive = False
        self.newTest = False

        self.PinControl = PinControlUI.Pin_Control(None, wx.ID_ANY, "")
        
        #Load up combo box.
        preferred_index = -1
        self.Port_Connect.Clear()
        for n, (portname, desc, hwid) in enumerate(sorted(PinControlUI.SerialComm.serial.tools.list_ports.comports())):
            self.Port_Connect.Append(u'{} - {}'.format(portname, desc))
            
        self.Port_Connect.SetSelection(preferred_index)
        self.__attach_events()
        self.loadTests()


        self.test = None #Currently loaded test
        self.currentStage = None #Currently loaded stage.
        

    def __attach_events(self):

        self.Connect_Button.Bind(wx.EVT_BUTTON, self.ConnectPort)
        self.ShowPinUI_Button.Bind(wx.EVT_BUTTON, self.showPinUI)
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Load_Test.Bind(wx.EVT_BUTTON, self.LoadTestPushed)
        self.Next_Step_Button.Bind(wx.EVT_BUTTON, self.nextStepPushed)
        self.createNewTestButton.Bind(wx.EVT_BUTTON, self.onCreateNewTest)
        self.Notebook.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.onNotebookPageChange)
        self.clearNewTestValuesButton.Bind(wx.EVT_BUTTON, self.onClearAllValues)
        self.NewTestCreatorPreviousStage.Bind(wx.EVT_BUTTON, self.onNewTestPreviousStage)
        self.NewTestCreatorNextStage.Bind(wx.EVT_BUTTON, self.onNewTestNextStage)
        self.NewTestCreatorFinishTestButton.Bind(wx.EVT_BUTTON, self.OnNewTestFinishTest)
        self.NewTestCreatorSelectImage.Bind(wx.EVT_BUTTON, self.onNewTestSelectImage)
        #self.PortConnect()

    #loadTests - load in the test procedures located in test folder.
    #Then populate the list with them.
    def loadTests(self):
        p = Path('.') #Using pathlib - replacement of os.
        p2 = p / "Tests"
        if p2.exists():
            for x in p2.iterdir():
                if x.is_dir():
                    self.List_Of_Tests.Append(x.name)
        else:
            print("error - Tests directory not found.")            


    def ConnectPort(self, events):
        self.PinControl.ExternalStartSerial(self.Port_Connect.GetSelection())
        #Disable the connect button.

    def showPinUI(self, events):
        self.PinControl.Show()
        #TODO: Change the PinControlUI to be able to be 'closed', made
        #not visible anymore and then able to be made visible again.

    def OnClose(self, event):
        if self.stopClose:
            if wx.MessageBox("File has not been saved, continue closing?", "Please confirm below.", wx.ICON_QUESTION | wx.YES_NO) != wx.YES:
                event.veto()
                return

        #self.PinControl.stopUIThread()
        self.PinControl.closeSelf()
        self.Destroy()
        exit(0)

    #Load in the files for the test sequence after button click.
    def loadTestSequence(self, path):
        #Get a list of all files within the test folder
        if path.exists():
            logging.info("path exists")
            for x in path.iterdir():
                if x.is_file():
                    #logging.debug("x is file")
                    if x.suffix == '.txt':
                        #logging.debug("txt file found.")
                        self.test = TestSequence.TestSequence()
                        self.test.initialLoadIn(self.PinControl.SerialLine.PinsList, x)
                    if x.suffix == '.png' or x.suffix == '.jpg' or x.suffix == '.bmp':
                        #If the suffix is an image,
                        pass
        else:
            print("Error  - file not found/path does not exist.")

        #Find the .txt, then parse in as json
        #Load the rest of the images, store in image container.
        #Need to make a class to contain it.

    #Load the Test selected, or say no test selected/display test error.
    def LoadTestPushed(self, event):
        #On load of test, open the test tab.
        if (self.List_Of_Tests.GetSelection()==-1):
            wx.MessageBox("Nothing selected.  No action able to be performed", "No Selected Test",  wx.OK | wx.ICON_INFORMATION)
            return
        #Initiate loading test in new tab.
        #Switch tab
        p = Path('.')
        p = p/"Tests"/self.List_Of_Tests.GetStringSelection()
        logging.debug(p)
        self.loadTestSequence(p)
        #logging.info(self.test.exportJsonFile())
        self.Notebook.SetSelection(1)
        self.testActive = True
        self.test.FolderPath = p
        self.startTest()


    #next step pushed
    def nextStepPushed(self, event):
        if self.testActive:
            if self.test.isNextTest():
                if self.currentStage.passPinCheck():
                    self.loadNextTestStage()
                else:
                    #Does not pass check
                    #Code this in.
                    pass
            else:
                self.finishTest()
        


    def startTest(self):
        self.Current_Test_Label.SetLabel("Current Test: {}".format(self.test.name))
        self.loadNextTestStage()

    def loadNextTestStage(self):
        self.currentStage = self.test.getNextTest()
        #Load in the image
        
        for x in self.test.FolderPath.iterdir():
            logging.debug("Checking for image {}".format(self.currentStage.imgpath))
            if x.is_file():
                logging.debug(x.name)
                if x.name==self.currentStage.imgpath:
                    logging.debug("Found image, updating.")
                    self.Next_Step_Image.SetBitmap(wx.Bitmap(str(x.resolve()), wx.BITMAP_TYPE_ANY))
        #Load in the test stage number, and adjust the status below
        self.Test_Status_Label.SetLabel("Stage {} out of {}".format(self.test.current_test, self.test.getNumStages()))
        #Change Operation to say Description.
        self.Stage_Description_Label.SetLabel("{}".format(self.currentStage.description))
        pass

    def finishTest(self):
        wx.MessageBox("Test finished - passed.", "Test Passed",  wx.OK | wx.ICON_INFORMATION)
        self.testActive = False
        self.Notebook.SetSelection(0)




#####################Handling test creation#########################
    def onNotebookPageChange(self, event):
        if self.Notebook.GetSelection()==3:
            if not self.newTest:
                wx.MessageBox("No test being created - please create a new test before creating stages.", "No Test Creation in Progress",  wx.OK | wx.ICON_INFORMATION)
                self.Notebook.SetSelection(2)
        #Check to see if a new test is being created,
        #if not then move new test away.
    
    def onCreateNewTest(self, event):
        if not self.newTest:
            self.newTest = True

            #Make a new test object,
            #Store in the pins used, name and description.

            self.test = TestSequence.TestSequence()
            self.test.name = self.TestNameTextbox.GetValue()
            self.test.description = self.Test_Description.GetValue()
            self.getTestPinsList() #Load in the pins that will be used for this test

            #Set up the test creation tab
            self.NewTestCreatorTestName.SetLabelText("Test Name: {}".format(self.test.name))
        
            self.Notebook.SetSelection(3)
        
        else:
            wx.MessageBox("Test already being created.", "Test Creation in Progress.",  wx.OK | wx.ICON_INFORMATION)
        #On create new test - create a new test object,
        #Move to NewTestCreator tab

    #getTestPinsList() -
    #On creating a new test, this goes through and finds each active pin
    #that will be used.
    #Also enables the pins in the stage creation menu.
    def getTestPinsList(self):
        for x in range(1,13):
            if eval("self.PinX1_{}Select.GetSelection()".format(x))!=2:
                exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(x+53, x, x))
                exec("self.PinX1_{}_Stage_Mode_Select.Enable(True)".format(x))
                exec("self.PinX1_{}_Stage_Value.Enable(True)".format(x))

                #Add to the test creator tab.
        if eval("self.PinX1_{}Select.GetSelection()".format(13))!=1:
            exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(2, 13, 13))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(13))

        for x in range(14, 18):
            if eval("self.PinX1_{}Select.GetSelection()".format(x))!=1:
                exec("self.test.TestPinsList.addPin({}, self.PinX1_{}Select.GetSelection(), 0, self.PinX1_{}Description.GetValue())".format(x-11, x, x))
                exec("self.PinX1_{}_Stage_Value.Enable(True)".format(x))

        for z in range(1,9):
            if eval("self.PinX2_{}Select.GetSelection()".format(z))!=1:
                exec("self.test.TestPinsList.addPin({}, self.PinX2_{}Select.GetSelection(), 0, self.PinX2_{}Description.GetValue())".format(z+21, z, z))
                exec("self.PinX2_{}_Stage_Mode_Select.Enable(True)".format(z))


    def onClearAllValues(self, event):
        #All the values are reset for the new test creator tab
        for x in range(1,14):
            exec("self.PinX1_{}Select.SetSelection(2)".format(x))
            exec("self.PinX1_{}Description.SetValue('Description')".format(x))
            if x!=13:
                exec("self.PinX1_{}_Stage_Mode_Select.Enable(False)".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))
        for x in range(14, 18):
            exec("self.PinX1_{}Select.SetSelection(1)".format(x))
            exec("self.PinX1_{}Description.SetValue('Description')".format(x))
            exec("self.PinX1_{}_Stage_Value.Enable(False)".format(x))

        for z in range(1,9):
            exec("self.PinX2_{}Select.SetSelection(1)".format(z))
            exec("self.PinX2_{}Description.SetValue('Description')".format(z))
            exec("self.PinX2_{}_Stage_Mode_Select.Enable(False)".format(z))

    #onNewTestStage() - when the new test next stage button is clicked.
    def onNewTestNextStage(self, event):
        self.test.current_test+=1
        
        #Make sure all necessary values actually exist
        
        #Check for existing img path, and write image to folder.
        
        #Check for pins having values to check

        #Check for 

        
        #Store all the values into the test stage object
        
        self.test.testStages.append(TestSequence.testStage(self.test.current_test, self.NewTestCreatorDescription.GetValue(), self.test.currentImgPath, ))

        #Write the image to folder
        #Increment stage levels
        pass

    def onNewTestPreviousStage(self, event):
        #
        pass

    def onNewTestFinishTest(self, event):
        #
        pass

    def onResultViewer(self, event):
        #
        pass


    def onNewTestSelectImage(self, event):
        #Open a box to select the image for a certain stage.
        with wx.FileDialog(self, "Open Image", wildcard = "Image Files (*.png, *.jpg)|*.png, *.jpg",
            style=wx.FD_OPEN | wd.FD_FILE_MUST_EXIST) as fileDialog:
            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return
            pathname = fileDialog.GetPath()
            self.test.currentImgPath = pathname
    



###############################################################################################################################################




class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
