#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Dec 17 16:35:29 2020
#

import wx
import SerialComm
import threading
import SerialMonitor

import time

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

'''
Box Pin Layout - as of 2/8/21 
X1_1 - AD0 - 54
X1_2 - AD1 - 55
X1_3 - AD2 - 56
X1_4 - AD3 - 57
X1_5 - AD4 - 58
X1_6 - AD5 - 59
X1_7 - AD6 - 60
X1_8 - AD7 - 61
X1_9 - AD8 - 62
X1_10 - AD9 - 63
X1_11 - AD10 - 64
X1_12 - AD11 - 65
X1_13 - PWM2 - 2
X1_14 - PWM3 - 3
X1_15 - PWM4 - 4
X1_16 - PWM5 - 5
X1_17 - PWM6 - 6
X1_18 - 5V


X2_1 - K1 (12V) - 22
X2_2 - K2 (12V) - 23
X2_3 - K3 (12V) - 24
X2_4 - K4 (12V) - 25
X2_5 - K5 (24V) - 26
X2_6 - K6 (24V) - 27
X2_7 - K7 (24V) - 28
X2_8 - K8 (24V) - 29


X2_10 - GND
X2_11 - GND
X2_12 - GND


'''



class Pin_Control(wx.Frame):

    
    def __init__(self, *args, **kwds):
        # begin wxGlade: Pin_Control.__init__
        self.SerialLine = SerialComm.SerialHandler()
        self.SerialLine.point_to_main = self

        self.SerialMonitor = None

        self.SerialMonitor = SerialMonitor.Serial_Monitor(None, wx.ID_ANY, "")


        self.thread = None
        self.alive = threading.Event()

        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1349, 593))
        self.Baud_Rate_Combo_Box = wx.ComboBox(self, wx.ID_ANY, choices=["9600", "19200", "38400", "57600", "115200"], style=wx.CB_DROPDOWN)
        self.Baud_Rate_Combo_Box.SetSelection(0)
        self.PortComboBox = wx.ComboBox(self, wx.ID_ANY, choices=[], style=0)
        self.Connection_Status_Display = wx.TextCtrl(self, wx.ID_ANY, "")
        self.Start_Connection_Button = wx.Button(self, wx.ID_ANY, "Start Connection")
        self.Stop_Connection_Button = wx.Button(self, wx.ID_ANY, "Stop Connection")
        self.Show_Serial_Monitor = wx.Button(self, wx.ID_ANY, "Show Serial Monitor")
        self.Pin_22_Enable = wx.CheckBox(self, wx.ID_ANY, "22")
        self.Pin_22_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_22_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_23_Enable = wx.CheckBox(self, wx.ID_ANY, "23")
        self.Pin_23_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_23_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_24_Enable = wx.CheckBox(self, wx.ID_ANY, "24")
        self.Pin_24_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_24_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_25_Enable = wx.CheckBox(self, wx.ID_ANY, "25")
        self.Pin_25_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_25_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_26_Enable = wx.CheckBox(self, wx.ID_ANY, "26")
        self.Pin_26_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_26_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_27_Enable = wx.CheckBox(self, wx.ID_ANY, "27")
        self.Pin_27_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_27_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_28_Enable = wx.CheckBox(self, wx.ID_ANY, "28")
        self.Pin_28_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_28_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_29_Enable = wx.CheckBox(self, wx.ID_ANY, "29")
        self.Pin_29_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_29_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_30_Enable = wx.CheckBox(self, wx.ID_ANY, "30")
        self.Pin_30_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_30_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_31_Enable = wx.CheckBox(self, wx.ID_ANY, "31")
        self.Pin_31_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_31_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_32_Enable = wx.CheckBox(self, wx.ID_ANY, "32")
        self.Pin_32_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_32_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_33_Enable = wx.CheckBox(self, wx.ID_ANY, "33")
        self.Pin_33_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_33_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_34_Enable = wx.CheckBox(self, wx.ID_ANY, "34")
        self.Pin_34_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_34_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_35_Enable = wx.CheckBox(self, wx.ID_ANY, "35")
        self.Pin_35_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_35_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_36_Enable = wx.CheckBox(self, wx.ID_ANY, "36")
        self.Pin_36_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_36_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_37_Enable = wx.CheckBox(self, wx.ID_ANY, "37")
        self.Pin_37_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_37_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_38_Enable = wx.CheckBox(self, wx.ID_ANY, "38")
        self.Pin_38_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_38_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_39_Enable = wx.CheckBox(self, wx.ID_ANY, "39")
        self.Pin_39_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_39_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_40_Enable = wx.CheckBox(self, wx.ID_ANY, "40")
        self.Pin_40_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_40_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_41_Enable = wx.CheckBox(self, wx.ID_ANY, "41")
        self.Pin_41_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_41_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_42_Enable = wx.CheckBox(self, wx.ID_ANY, "42")
        self.Pin_42_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_42_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_43_Enable = wx.CheckBox(self, wx.ID_ANY, "43")
        self.Pin_43_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_43_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_44_Enable = wx.CheckBox(self, wx.ID_ANY, "44")
        self.Pin_44_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_44_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_45_Enable = wx.CheckBox(self, wx.ID_ANY, "45")
        self.Pin_45_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_45_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_46_Enable = wx.CheckBox(self, wx.ID_ANY, "46")
        self.Pin_46_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_46_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_47_Enable = wx.CheckBox(self, wx.ID_ANY, "47")
        self.Pin_47_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_47_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_48_Enable = wx.CheckBox(self, wx.ID_ANY, "48")
        self.Pin_48_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_48_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_49_Enable = wx.CheckBox(self, wx.ID_ANY, "49")
        self.Pin_49_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_49_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_50_Enable = wx.CheckBox(self, wx.ID_ANY, "50")
        self.Pin_50_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_50_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_51_Enable = wx.CheckBox(self, wx.ID_ANY, "51")
        self.Pin_51_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_51_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_52_Enable = wx.CheckBox(self, wx.ID_ANY, "52")
        self.Pin_52_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_52_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_53_Enable = wx.CheckBox(self, wx.ID_ANY, "53")
        self.Pin_53_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_53_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_54_Enable = wx.CheckBox(self, wx.ID_ANY, "A0")
        self.Pin_54_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_54_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_55_Enable = wx.CheckBox(self, wx.ID_ANY, "A1")
        self.Pin_55_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_55_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_56_Enable = wx.CheckBox(self, wx.ID_ANY, "A2")
        self.Pin_56_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_56_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_57_Enable = wx.CheckBox(self, wx.ID_ANY, "A3")
        self.Pin_57_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_57_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_58_Enable = wx.CheckBox(self, wx.ID_ANY, "A4")
        self.Pin_58_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_58_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_59_Enable = wx.CheckBox(self, wx.ID_ANY, "A5")
        self.Pin_59_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_59_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_60_Enable = wx.CheckBox(self, wx.ID_ANY, "A6")
        self.Pin_60_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_60_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_61_Enable = wx.CheckBox(self, wx.ID_ANY, "A7")
        self.Pin_61_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_61_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_62_Enable = wx.CheckBox(self, wx.ID_ANY, "A8")
        self.Pin_62_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_62_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_63_Enable = wx.CheckBox(self, wx.ID_ANY, "A9")
        self.Pin_63_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_63_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_64_Enable = wx.CheckBox(self, wx.ID_ANY, "A10")
        self.Pin_64_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_64_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_65_Enable = wx.CheckBox(self, wx.ID_ANY, "A11")
        self.Pin_65_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_65_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_66_Enable = wx.CheckBox(self, wx.ID_ANY, "A12")
        self.Pin_66_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_66_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_67_Enable = wx.CheckBox(self, wx.ID_ANY, "A13")
        self.Pin_67_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_67_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_68_Enable = wx.CheckBox(self, wx.ID_ANY, "A14")
        self.Pin_68_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_68_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_69_Enable = wx.CheckBox(self, wx.ID_ANY, "A15")
        self.Pin_69_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_69_Mode_Box = wx.ComboBox(self, wx.ID_ANY, choices=["Input", "Output"], style=wx.CB_DROPDOWN)
        self.Pin_2_Enable = wx.CheckBox(self, wx.ID_ANY, "2")
        self.Pin_2_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_3_Enable = wx.CheckBox(self, wx.ID_ANY, "3")
        self.Pin_3_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_4_Enable = wx.CheckBox(self, wx.ID_ANY, "4")
        self.Pin_4_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_5_Enable = wx.CheckBox(self, wx.ID_ANY, "5")
        self.Pin_5_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_6_Enable = wx.CheckBox(self, wx.ID_ANY, "6")
        self.Pin_6_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_7_Enable = wx.CheckBox(self, wx.ID_ANY, "7")
        self.Pin_7_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_8_Enable = wx.CheckBox(self, wx.ID_ANY, "8")
        self.Pin_8_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_9_Enable = wx.CheckBox(self, wx.ID_ANY, "9")
        self.Pin_9_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_10_Enable = wx.CheckBox(self, wx.ID_ANY, "10")
        self.Pin_10_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_11_Enable = wx.CheckBox(self, wx.ID_ANY, "11")
        self.Pin_11_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_12_Enable = wx.CheckBox(self, wx.ID_ANY, "12")
        self.Pin_12_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Pin_13_Enable = wx.CheckBox(self, wx.ID_ANY, "13")
        self.Pin_13_Status = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.Connection_Time_Display = wx.TextCtrl(self, wx.ID_ANY, "1500")
        self.Configure_Pin_In_Out = wx.Button(self, wx.ID_ANY, "Configure Pin In/Out")
        self.Update_Output = wx.Button(self, wx.ID_ANY, "Update Pin Output")
        self.Configure_Output_Time = wx.Button(self, wx.ID_ANY, "Configure Output Time")
        self.Reset_Pin_Button = wx.Button(self, wx.ID_ANY, "Reset Pins")
        self.Full_Reset_Button = wx.Button(self, wx.ID_ANY, "Full Reset")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.__attach_events()

        self.startUIThread()

    def __set_properties(self):
        #TODO: Assign pin A as pin 8.  Everytime A appears, replace w/ 8

        #Note:: Analog input pins begin w/ A.  Replaced with 8 for the purposes of this program.
        # begin wxGlade: Pin_Control.__set_properties
        self.SetTitle("Test Box Pin Control")
        self.Stop_Connection_Button.Enable(False)
        self.Pin_22_Status.SetMinSize((40, 23))
        self.Pin_22_Mode_Box.SetMinSize((60, 23))
        self.Pin_22_Mode_Box.SetSelection(0)
        self.Pin_23_Status.SetMinSize((40, 23))
        self.Pin_23_Mode_Box.SetMinSize((60, 23))
        self.Pin_23_Mode_Box.SetSelection(0)
        self.Pin_24_Status.SetMinSize((40, 23))
        self.Pin_24_Mode_Box.SetMinSize((60, 23))
        self.Pin_24_Mode_Box.SetSelection(0)
        self.Pin_25_Status.SetMinSize((40, 23))
        self.Pin_25_Mode_Box.SetMinSize((60, 23))
        self.Pin_25_Mode_Box.SetSelection(0)
        self.Pin_26_Status.SetMinSize((40, 23))
        self.Pin_26_Mode_Box.SetMinSize((60, 23))
        self.Pin_26_Mode_Box.SetSelection(0)
        self.Pin_27_Status.SetMinSize((40, 23))
        self.Pin_27_Mode_Box.SetMinSize((60, 23))
        self.Pin_27_Mode_Box.SetSelection(0)
        self.Pin_28_Status.SetMinSize((40, 23))
        self.Pin_28_Mode_Box.SetMinSize((60, 23))
        self.Pin_28_Mode_Box.SetSelection(0)
        self.Pin_29_Status.SetMinSize((40, 23))
        self.Pin_29_Mode_Box.SetMinSize((60, 23))
        self.Pin_29_Mode_Box.SetSelection(0)
        self.Pin_30_Status.SetMinSize((40, 23))
        self.Pin_30_Mode_Box.SetMinSize((60, 23))
        self.Pin_30_Mode_Box.SetSelection(0)
        self.Pin_31_Status.SetMinSize((40, 23))
        self.Pin_31_Mode_Box.SetMinSize((60, 23))
        self.Pin_31_Mode_Box.SetSelection(0)
        self.Pin_32_Status.SetMinSize((40, 23))
        self.Pin_32_Mode_Box.SetMinSize((60, 23))
        self.Pin_32_Mode_Box.SetSelection(0)
        self.Pin_33_Status.SetMinSize((40, 23))
        self.Pin_33_Mode_Box.SetMinSize((60, 23))
        self.Pin_33_Mode_Box.SetSelection(0)
        self.Pin_34_Status.SetMinSize((40, 23))
        self.Pin_34_Mode_Box.SetMinSize((60, 23))
        self.Pin_34_Mode_Box.SetSelection(0)
        self.Pin_35_Status.SetMinSize((40, 23))
        self.Pin_35_Mode_Box.SetMinSize((60, 23))
        self.Pin_35_Mode_Box.SetSelection(0)
        self.Pin_36_Status.SetMinSize((40, 23))
        self.Pin_36_Mode_Box.SetMinSize((60, 23))
        self.Pin_36_Mode_Box.SetSelection(0)
        self.Pin_37_Status.SetMinSize((40, 23))
        self.Pin_37_Mode_Box.SetMinSize((60, 23))
        self.Pin_37_Mode_Box.SetSelection(0)
        self.Pin_38_Status.SetMinSize((40, 23))
        self.Pin_38_Mode_Box.SetMinSize((60, 23))
        self.Pin_38_Mode_Box.SetSelection(0)
        self.Pin_39_Status.SetMinSize((40, 23))
        self.Pin_39_Mode_Box.SetMinSize((60, 23))
        self.Pin_39_Mode_Box.SetSelection(0)
        self.Pin_40_Status.SetMinSize((40, 23))
        self.Pin_40_Mode_Box.SetMinSize((60, 23))
        self.Pin_40_Mode_Box.SetSelection(0)
        self.Pin_41_Status.SetMinSize((40, 23))
        self.Pin_41_Mode_Box.SetMinSize((60, 23))
        self.Pin_41_Mode_Box.SetSelection(0)
        self.Pin_42_Status.SetMinSize((40, 23))
        self.Pin_42_Mode_Box.SetMinSize((60, 23))
        self.Pin_42_Mode_Box.SetSelection(0)
        self.Pin_43_Status.SetMinSize((40, 23))
        self.Pin_43_Mode_Box.SetMinSize((60, 23))
        self.Pin_43_Mode_Box.SetSelection(0)
        self.Pin_44_Status.SetMinSize((40, 23))
        self.Pin_44_Mode_Box.SetMinSize((60, 23))
        self.Pin_44_Mode_Box.SetSelection(0)
        self.Pin_45_Status.SetMinSize((40, 23))
        self.Pin_45_Mode_Box.SetMinSize((60, 23))
        self.Pin_45_Mode_Box.SetSelection(0)
        self.Pin_46_Status.SetMinSize((40, 23))
        self.Pin_46_Mode_Box.SetMinSize((60, 23))
        self.Pin_46_Mode_Box.SetSelection(0)
        self.Pin_47_Status.SetMinSize((40, 23))
        self.Pin_47_Mode_Box.SetMinSize((60, 23))
        self.Pin_47_Mode_Box.SetSelection(0)
        self.Pin_48_Status.SetMinSize((40, 23))
        self.Pin_48_Mode_Box.SetMinSize((60, 23))
        self.Pin_48_Mode_Box.SetSelection(0)
        self.Pin_49_Status.SetMinSize((40, 23))
        self.Pin_49_Mode_Box.SetMinSize((60, 23))
        self.Pin_49_Mode_Box.SetSelection(0)
        self.Pin_50_Status.SetMinSize((40, 23))
        self.Pin_50_Mode_Box.SetMinSize((60, 23))
        self.Pin_50_Mode_Box.SetSelection(0)
        self.Pin_51_Status.SetMinSize((40, 23))
        self.Pin_51_Mode_Box.SetMinSize((60, 23))
        self.Pin_51_Mode_Box.SetSelection(0)
        self.Pin_52_Status.SetMinSize((40, 23))
        self.Pin_52_Mode_Box.SetMinSize((60, 23))
        self.Pin_52_Mode_Box.SetSelection(0)
        self.Pin_53_Status.SetMinSize((40, 23))
        self.Pin_53_Mode_Box.SetMinSize((60, 23))
        self.Pin_53_Mode_Box.SetSelection(0)
        self.Pin_54_Status.SetMinSize((40, 23))
        self.Pin_54_Mode_Box.SetMinSize((60, 23))
        self.Pin_54_Mode_Box.SetSelection(0)
        self.Pin_55_Status.SetMinSize((40, 23))
        self.Pin_55_Mode_Box.SetMinSize((60, 23))
        self.Pin_55_Mode_Box.SetSelection(0)
        self.Pin_56_Status.SetMinSize((40, 23))
        self.Pin_56_Mode_Box.SetMinSize((60, 23))
        self.Pin_56_Mode_Box.SetSelection(0)
        self.Pin_57_Status.SetMinSize((40, 23))
        self.Pin_57_Mode_Box.SetMinSize((60, 23))
        self.Pin_57_Mode_Box.SetSelection(0)
        self.Pin_58_Status.SetMinSize((40, 23))
        self.Pin_58_Mode_Box.SetMinSize((60, 23))
        self.Pin_58_Mode_Box.SetSelection(0)
        self.Pin_59_Status.SetMinSize((40, 23))
        self.Pin_59_Mode_Box.SetMinSize((60, 23))
        self.Pin_59_Mode_Box.SetSelection(0)
        self.Pin_60_Status.SetMinSize((40, 23))
        self.Pin_60_Mode_Box.SetMinSize((60, 23))
        self.Pin_60_Mode_Box.SetSelection(0)
        self.Pin_61_Status.SetMinSize((40, 23))
        self.Pin_61_Mode_Box.SetMinSize((60, 23))
        self.Pin_61_Mode_Box.SetSelection(0)
        self.Pin_62_Status.SetMinSize((40, 23))
        self.Pin_62_Mode_Box.SetMinSize((60, 23))
        self.Pin_62_Mode_Box.SetSelection(0)
        self.Pin_63_Status.SetMinSize((40, 23))
        self.Pin_63_Mode_Box.SetMinSize((60, 23))
        self.Pin_63_Mode_Box.SetSelection(0)
        self.Pin_64_Status.SetMinSize((40, 23))
        self.Pin_64_Mode_Box.SetMinSize((60, 23))
        self.Pin_64_Mode_Box.SetSelection(0)
        self.Pin_65_Status.SetMinSize((40, 23))
        self.Pin_65_Mode_Box.SetMinSize((60, 23))
        self.Pin_65_Mode_Box.SetSelection(0)
        self.Pin_66_Status.SetMinSize((40, 23))
        self.Pin_66_Mode_Box.SetMinSize((60, 23))
        self.Pin_66_Mode_Box.SetSelection(0)
        self.Pin_67_Status.SetMinSize((40, 23))
        self.Pin_67_Mode_Box.SetMinSize((60, 23))
        self.Pin_67_Mode_Box.SetSelection(0)
        self.Pin_68_Status.SetMinSize((40, 23))
        self.Pin_68_Mode_Box.SetMinSize((60, 23))
        self.Pin_68_Mode_Box.SetSelection(0)
        self.Pin_69_Status.SetMinSize((40, 23))
        self.Pin_69_Mode_Box.SetMinSize((60, 23))
        self.Pin_69_Mode_Box.SetSelection(0)
        self.Pin_2_Status.SetMinSize((60, 23))
        self.Pin_3_Status.SetMinSize((60, 23))
        self.Pin_4_Status.SetMinSize((60, 23))
        self.Pin_5_Status.SetMinSize((60, 23))
        self.Pin_6_Status.SetMinSize((60, 23))
        self.Pin_7_Status.SetMinSize((60, 23))
        self.Pin_8_Status.SetMinSize((60, 23))
        self.Pin_9_Status.SetMinSize((60, 23))
        self.Pin_10_Status.SetMinSize((60, 23))
        self.Pin_11_Status.SetMinSize((60, 23))
        self.Pin_12_Status.SetMinSize((60, 23))
        self.Pin_13_Status.SetMinSize((60, 23))
        # end wxGlade

        # fill in ports and select current setting
        preferred_index = -1
        self.PortComboBox.Clear()
        self.ports = []
        for n, (portname, desc, hwid) in enumerate(sorted(SerialComm.serial.tools.list_ports.comports())):
            self.PortComboBox.Append(u'{} - {}'.format(portname, desc))
            self.ports.append(portname)
        self.PortComboBox.SetSelection(preferred_index)


    def __do_layout(self):
        # begin wxGlade: Pin_Control.__do_layout
        Main_Sizer = wx.BoxSizer(wx.VERTICAL)
        Button_Sizer = wx.BoxSizer(wx.VERTICAL)
        Actuator_Button = wx.BoxSizer(wx.HORIZONTAL)
        Buttons = wx.BoxSizer(wx.HORIZONTAL)
        All_Pin_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        PWM_Output_Pins = wx.BoxSizer(wx.VERTICAL)
        PWM_Output_Pin_Grid = wx.GridSizer(4, 3, 0, 0)
        Pin_13_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_12_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_11_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_10_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_9_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_8_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_7_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_6_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_5_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_4_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_3_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_2_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Analog_Input_Pins_Sizer = wx.BoxSizer(wx.VERTICAL)
        Analog_Pin_Grid = wx.GridSizer(6, 3, 0, 0)
        Pin_69_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_68_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_67_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_66_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_65_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_64_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_63_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_62_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_61_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_60_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_59_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_58_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_57_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_56_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_55_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_54_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        GPIO_Pins = wx.BoxSizer(wx.VERTICAL)
        GPIO_Pin_Grid = wx.GridSizer(11, 3, 0, 0)
        Pin_53_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_52_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_51_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_50_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_49_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_48_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_47_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_46_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_45_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_44_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_43_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_42_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_41_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_40_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_39_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_38_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_37_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_36_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_35_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_34_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_33_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_32_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_31_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_30_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_29_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_28_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_27_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_26_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_25_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_24_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_23_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Pin_22_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Serial_Control_Sizer = wx.BoxSizer(wx.VERTICAL)
        Serial_Comms_Connection_Manager_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Serial_Comms_Options_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        Baud_Rate_Label = wx.StaticText(self, wx.ID_ANY, "Baud Rate:")
        Serial_Comms_Options_Sizer.Add(Baud_Rate_Label, 0, 0, 0)
        Serial_Comms_Options_Sizer.Add(self.Baud_Rate_Combo_Box, 0, 0, 0)
        PortLabel = wx.StaticText(self, wx.ID_ANY, "Port: ")
        Serial_Comms_Options_Sizer.Add(PortLabel, 0, 0, 0)
        Serial_Comms_Options_Sizer.Add(self.PortComboBox, 0, 0, 0)
        Serial_Control_Sizer.Add(Serial_Comms_Options_Sizer, 1, wx.EXPAND, 0)
        Connection_Status_Label = wx.StaticText(self, wx.ID_ANY, "Connection Status:")
        Serial_Comms_Connection_Manager_Sizer.Add(Connection_Status_Label, 0, 0, 0)
        Serial_Comms_Connection_Manager_Sizer.Add(self.Connection_Status_Display, 0, 0, 0)
        Serial_Comms_Connection_Manager_Sizer.Add(self.Start_Connection_Button, 0, 0, 0)
        Serial_Comms_Connection_Manager_Sizer.Add(self.Stop_Connection_Button, 0, 0, 0)
        Serial_Comms_Connection_Manager_Sizer.Add(self.Show_Serial_Monitor, 0, 0, 0)
        Serial_Control_Sizer.Add(Serial_Comms_Connection_Manager_Sizer, 1, wx.EXPAND, 0)
        Main_Sizer.Add(Serial_Control_Sizer, 1, wx.EXPAND, 0)
        GPIO_Pin_Label = wx.StaticText(self, wx.ID_ANY, " GPIO Pins ", style=wx.ALIGN_CENTER)
        GPIO_Pins.Add(GPIO_Pin_Label, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        Pin_22_Sizer.Add(self.Pin_22_Enable, 0, 0, 0)
        Pin_22_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_22_Sizer.Add(Pin_22_Status_Label, 0, wx.ALL, 1)
        Pin_22_Sizer.Add(self.Pin_22_Status, 0, wx.ALL, 2)
        Pin_22_Sizer.Add(self.Pin_22_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_22_Sizer, 1, wx.EXPAND, 0)
        Pin_23_Sizer.Add(self.Pin_23_Enable, 0, 0, 0)
        Pin_23_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_23_Sizer.Add(Pin_23_Status_Label, 0, wx.ALL, 1)
        Pin_23_Sizer.Add(self.Pin_23_Status, 0, wx.ALL, 2)
        Pin_23_Sizer.Add(self.Pin_23_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_23_Sizer, 1, wx.EXPAND, 0)
        Pin_24_Sizer.Add(self.Pin_24_Enable, 0, 0, 0)
        Pin_24_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_24_Sizer.Add(Pin_24_Status_Label, 0, wx.ALL, 1)
        Pin_24_Sizer.Add(self.Pin_24_Status, 0, wx.ALL, 1)
        Pin_24_Sizer.Add(self.Pin_24_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_24_Sizer, 0, wx.EXPAND, 0)
        Pin_25_Sizer.Add(self.Pin_25_Enable, 0, 0, 0)
        Pin_25_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_25_Sizer.Add(Pin_25_Status_Label, 0, wx.ALL, 1)
        Pin_25_Sizer.Add(self.Pin_25_Status, 0, wx.ALL, 2)
        Pin_25_Sizer.Add(self.Pin_25_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_25_Sizer, 0, wx.EXPAND, 0)
        Pin_26_Sizer.Add(self.Pin_26_Enable, 0, 0, 0)
        Pin_26_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_26_Sizer.Add(Pin_26_Status_Label, 0, wx.ALL, 1)
        Pin_26_Sizer.Add(self.Pin_26_Status, 0, wx.ALL, 2)
        Pin_26_Sizer.Add(self.Pin_26_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_26_Sizer, 1, wx.EXPAND, 0)
        Pin_27_Sizer.Add(self.Pin_27_Enable, 0, 0, 0)
        Pin_27_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_27_Sizer.Add(Pin_27_Status_Label, 0, wx.ALL, 1)
        Pin_27_Sizer.Add(self.Pin_27_Status, 0, wx.ALL, 2)
        Pin_27_Sizer.Add(self.Pin_27_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_27_Sizer, 1, wx.EXPAND, 0)
        Pin_28_Sizer.Add(self.Pin_28_Enable, 0, 0, 0)
        Pin_28_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_28_Sizer.Add(Pin_28_Status_Label, 0, wx.ALL, 1)
        Pin_28_Sizer.Add(self.Pin_28_Status, 0, wx.ALL, 2)
        Pin_28_Sizer.Add(self.Pin_28_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_28_Sizer, 1, wx.EXPAND, 0)
        Pin_29_Sizer.Add(self.Pin_29_Enable, 0, 0, 0)
        Pin_29_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_29_Sizer.Add(Pin_29_Status_Label, 0, wx.ALL, 1)
        Pin_29_Sizer.Add(self.Pin_29_Status, 0, wx.ALL, 2)
        Pin_29_Sizer.Add(self.Pin_29_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_29_Sizer, 1, wx.EXPAND, 0)
        Pin_30_Sizer.Add(self.Pin_30_Enable, 0, 0, 0)
        Pin_30_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_30_Sizer.Add(Pin_30_Status_Label, 0, wx.ALL, 1)
        Pin_30_Sizer.Add(self.Pin_30_Status, 0, wx.ALL, 2)
        Pin_30_Sizer.Add(self.Pin_30_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_30_Sizer, 1, wx.EXPAND, 0)
        Pin_31_Sizer.Add(self.Pin_31_Enable, 0, 0, 0)
        Pin_31_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_31_Sizer.Add(Pin_31_Status_Label, 0, wx.ALL, 1)
        Pin_31_Sizer.Add(self.Pin_31_Status, 0, wx.ALL, 2)
        Pin_31_Sizer.Add(self.Pin_31_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_31_Sizer, 1, wx.EXPAND, 0)
        Pin_32_Sizer.Add(self.Pin_32_Enable, 0, 0, 0)
        Pin_32_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_32_Sizer.Add(Pin_32_Status_Label, 0, wx.ALL, 1)
        Pin_32_Sizer.Add(self.Pin_32_Status, 0, wx.ALL, 2)
        Pin_32_Sizer.Add(self.Pin_32_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_32_Sizer, 1, wx.EXPAND, 0)
        Pin_33_Sizer.Add(self.Pin_33_Enable, 0, 0, 0)
        Pin_33_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_33_Sizer.Add(Pin_33_Status_Label, 0, wx.ALL, 1)
        Pin_33_Sizer.Add(self.Pin_33_Status, 0, wx.ALL, 2)
        Pin_33_Sizer.Add(self.Pin_33_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_33_Sizer, 1, wx.EXPAND, 0)
        Pin_34_Sizer.Add(self.Pin_34_Enable, 0, 0, 0)
        Pin_34_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_34_Sizer.Add(Pin_34_Status_Label, 0, wx.ALL, 1)
        Pin_34_Sizer.Add(self.Pin_34_Status, 0, wx.ALL, 2)
        Pin_34_Sizer.Add(self.Pin_34_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_34_Sizer, 0, wx.EXPAND, 0)
        Pin_35_Sizer.Add(self.Pin_35_Enable, 0, 0, 0)
        Pin_35_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_35_Sizer.Add(Pin_35_Status_Label, 0, wx.ALL, 1)
        Pin_35_Sizer.Add(self.Pin_35_Status, 0, wx.ALL, 2)
        Pin_35_Sizer.Add(self.Pin_35_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_35_Sizer, 1, wx.EXPAND, 0)
        Pin_36_Sizer.Add(self.Pin_36_Enable, 0, 0, 0)
        Pin_36_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_36_Sizer.Add(Pin_36_Status_Label, 0, wx.ALL, 1)
        Pin_36_Sizer.Add(self.Pin_36_Status, 0, wx.ALL, 2)
        Pin_36_Sizer.Add(self.Pin_36_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_36_Sizer, 1, wx.EXPAND, 0)
        Pin_37_Sizer.Add(self.Pin_37_Enable, 0, 0, 0)
        Pin_37_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_37_Sizer.Add(Pin_37_Status_Label, 0, wx.ALL, 1)
        Pin_37_Sizer.Add(self.Pin_37_Status, 0, wx.ALL, 2)
        Pin_37_Sizer.Add(self.Pin_37_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_37_Sizer, 1, wx.EXPAND, 0)
        Pin_38_Sizer.Add(self.Pin_38_Enable, 0, 0, 0)
        Pin_38_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_38_Sizer.Add(Pin_38_Status_Label, 0, wx.ALL, 1)
        Pin_38_Sizer.Add(self.Pin_38_Status, 0, wx.ALL, 2)
        Pin_38_Sizer.Add(self.Pin_38_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_38_Sizer, 1, wx.EXPAND, 0)
        Pin_39_Sizer.Add(self.Pin_39_Enable, 0, 0, 0)
        Pin_39_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_39_Sizer.Add(Pin_39_Status_Label, 0, wx.ALL, 1)
        Pin_39_Sizer.Add(self.Pin_39_Status, 0, wx.ALL, 2)
        Pin_39_Sizer.Add(self.Pin_39_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_39_Sizer, 1, wx.EXPAND, 0)
        Pin_40_Sizer.Add(self.Pin_40_Enable, 0, 0, 0)
        Pin_40_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_40_Sizer.Add(Pin_40_Status_Label, 0, wx.ALL, 1)
        Pin_40_Sizer.Add(self.Pin_40_Status, 0, wx.ALL, 2)
        Pin_40_Sizer.Add(self.Pin_40_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_40_Sizer, 1, wx.EXPAND, 0)
        Pin_41_Sizer.Add(self.Pin_41_Enable, 0, 0, 0)
        Pin_41_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_41_Sizer.Add(Pin_41_Status_Label, 0, wx.ALL, 1)
        Pin_41_Sizer.Add(self.Pin_41_Status, 0, wx.ALL, 2)
        Pin_41_Sizer.Add(self.Pin_41_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_41_Sizer, 1, wx.EXPAND, 0)
        Pin_42_Sizer.Add(self.Pin_42_Enable, 0, 0, 0)
        Pin_42_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_42_Sizer.Add(Pin_42_Status_Label, 0, wx.ALL, 1)
        Pin_42_Sizer.Add(self.Pin_42_Status, 0, wx.ALL, 2)
        Pin_42_Sizer.Add(self.Pin_42_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_42_Sizer, 1, wx.EXPAND, 0)
        Pin_43_Sizer.Add(self.Pin_43_Enable, 0, 0, 0)
        Pin_43_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_43_Sizer.Add(Pin_43_Status_Label, 0, wx.ALL, 1)
        Pin_43_Sizer.Add(self.Pin_43_Status, 0, wx.ALL, 2)
        Pin_43_Sizer.Add(self.Pin_43_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_43_Sizer, 1, wx.EXPAND, 0)
        Pin_44_Sizer.Add(self.Pin_44_Enable, 0, 0, 0)
        Pin_44_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_44_Sizer.Add(Pin_44_Status_Label, 0, wx.ALL, 1)
        Pin_44_Sizer.Add(self.Pin_44_Status, 0, wx.ALL, 2)
        Pin_44_Sizer.Add(self.Pin_44_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_44_Sizer, 1, wx.EXPAND, 0)
        Pin_45_Sizer.Add(self.Pin_45_Enable, 0, 0, 0)
        Pin_45_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_45_Sizer.Add(Pin_45_Status_Label, 0, wx.ALL, 1)
        Pin_45_Sizer.Add(self.Pin_45_Status, 0, wx.ALL, 2)
        Pin_45_Sizer.Add(self.Pin_45_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_45_Sizer, 1, wx.EXPAND, 0)
        Pin_46_Sizer.Add(self.Pin_46_Enable, 0, 0, 0)
        Pin_46_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_46_Sizer.Add(Pin_46_Status_Label, 0, wx.ALL, 1)
        Pin_46_Sizer.Add(self.Pin_46_Status, 0, wx.ALL, 2)
        Pin_46_Sizer.Add(self.Pin_46_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_46_Sizer, 1, wx.EXPAND, 0)
        Pin_47_Sizer.Add(self.Pin_47_Enable, 0, 0, 0)
        Pin_47_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_47_Sizer.Add(Pin_47_Status_Label, 0, wx.ALL, 1)
        Pin_47_Sizer.Add(self.Pin_47_Status, 0, wx.ALL, 2)
        Pin_47_Sizer.Add(self.Pin_47_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_47_Sizer, 1, wx.EXPAND, 0)
        Pin_48_Sizer.Add(self.Pin_48_Enable, 0, 0, 0)
        Pin_48_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_48_Sizer.Add(Pin_48_Status_Label, 0, wx.ALL, 1)
        Pin_48_Sizer.Add(self.Pin_48_Status, 0, wx.ALL, 2)
        Pin_48_Sizer.Add(self.Pin_48_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_48_Sizer, 1, wx.EXPAND, 0)
        Pin_49_Sizer.Add(self.Pin_49_Enable, 0, 0, 0)
        Pin_49_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_49_Sizer.Add(Pin_49_Status_Label, 0, wx.ALL, 1)
        Pin_49_Sizer.Add(self.Pin_49_Status, 0, wx.ALL, 2)
        Pin_49_Sizer.Add(self.Pin_49_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_49_Sizer, 1, wx.EXPAND, 0)
        Pin_50_Sizer.Add(self.Pin_50_Enable, 0, 0, 0)
        Pin_50_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_50_Sizer.Add(Pin_50_Status_Label, 0, wx.ALL, 1)
        Pin_50_Sizer.Add(self.Pin_50_Status, 0, wx.ALL, 2)
        Pin_50_Sizer.Add(self.Pin_50_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_50_Sizer, 1, wx.EXPAND, 0)
        Pin_51_Sizer.Add(self.Pin_51_Enable, 0, 0, 0)
        Pin_51_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_51_Sizer.Add(Pin_51_Status_Label, 0, wx.ALL, 1)
        Pin_51_Sizer.Add(self.Pin_51_Status, 0, wx.ALL, 2)
        Pin_51_Sizer.Add(self.Pin_51_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_51_Sizer, 1, wx.EXPAND, 0)
        Pin_52_Sizer.Add(self.Pin_52_Enable, 0, 0, 0)
        Pin_52_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_52_Sizer.Add(Pin_52_Status_Label, 0, wx.ALL, 1)
        Pin_52_Sizer.Add(self.Pin_52_Status, 0, wx.ALL, 2)
        Pin_52_Sizer.Add(self.Pin_52_Mode_Box, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_52_Sizer, 1, wx.EXPAND, 0)
        Pin_53_Sizer.Add(self.Pin_53_Enable, 0, 0, 0)
        Pin_53_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_53_Sizer.Add(Pin_53_Status_Label, 0, wx.ALL, 1)
        Pin_53_Sizer.Add(self.Pin_53_Status, 0, wx.ALL, 2)
        Pin_53_Sizer.Add(self.Pin_53_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        GPIO_Pin_Grid.Add(Pin_53_Sizer, 1, wx.EXPAND, 0)
        Blank_Label = wx.StaticText(self, wx.ID_ANY, "")
        GPIO_Pin_Grid.Add(Blank_Label, 0, 0, 0)
        GPIO_Pins.Add(GPIO_Pin_Grid, 1, 0, 0)
        All_Pin_Sizer.Add(GPIO_Pins, 0, wx.FIXED_MINSIZE | wx.LEFT | wx.RIGHT, 1)
        Analog_Input_Pins_Label = wx.StaticText(self, wx.ID_ANY, "Analog Input Pins", style=wx.ALIGN_CENTER)
        Analog_Input_Pins_Sizer.Add(Analog_Input_Pins_Label, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        Pin_54_Sizer.Add(self.Pin_54_Enable, 0, 0, 0)
        Pin_54_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_54_Sizer.Add(Pin_54_Status_Label, 0, wx.ALL, 1)
        Pin_54_Sizer.Add(self.Pin_54_Status, 0, wx.ALL, 2)
        Pin_54_Sizer.Add(self.Pin_54_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_54_Sizer, 1, wx.EXPAND, 0)
        Pin_55_Sizer.Add(self.Pin_55_Enable, 0, 0, 0)
        Pin_55_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_55_Sizer.Add(Pin_55_Status_Label, 0, wx.ALL, 1)
        Pin_55_Sizer.Add(self.Pin_55_Status, 0, wx.ALL, 2)
        Pin_55_Sizer.Add(self.Pin_55_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_55_Sizer, 1, wx.EXPAND, 0)
        Pin_56_Sizer.Add(self.Pin_56_Enable, 0, 0, 0)
        Pin_56_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_56_Sizer.Add(Pin_56_Status_Label, 0, wx.ALL, 1)
        Pin_56_Sizer.Add(self.Pin_56_Status, 0, wx.ALL, 2)
        Pin_56_Sizer.Add(self.Pin_56_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_56_Sizer, 1, wx.EXPAND, 0)
        Pin_57_Sizer.Add(self.Pin_57_Enable, 0, 0, 0)
        Pin_57_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_57_Sizer.Add(Pin_57_Status_Label, 0, wx.ALL, 1)
        Pin_57_Sizer.Add(self.Pin_57_Status, 0, wx.ALL, 2)
        Pin_57_Sizer.Add(self.Pin_57_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_57_Sizer, 1, wx.EXPAND, 0)
        Pin_58_Sizer.Add(self.Pin_58_Enable, 0, 0, 0)
        Pin_58_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_58_Sizer.Add(Pin_58_Status_Label, 0, wx.ALL, 1)
        Pin_58_Sizer.Add(self.Pin_58_Status, 0, wx.ALL, 2)
        Pin_58_Sizer.Add(self.Pin_58_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_58_Sizer, 1, wx.EXPAND, 0)
        Pin_59_Sizer.Add(self.Pin_59_Enable, 0, 0, 0)
        Pin_59_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_59_Sizer.Add(Pin_59_Status_Label, 0, wx.ALL, 1)
        Pin_59_Sizer.Add(self.Pin_59_Status, 0, wx.ALL, 2)
        Pin_59_Sizer.Add(self.Pin_59_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_59_Sizer, 0, wx.EXPAND, 0)
        Pin_60_Sizer.Add(self.Pin_60_Enable, 0, 0, 0)
        Pin_60_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_60_Sizer.Add(Pin_60_Status_Label, 0, wx.ALL, 1)
        Pin_60_Sizer.Add(self.Pin_60_Status, 0, wx.ALL, 2)
        Pin_60_Sizer.Add(self.Pin_60_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_60_Sizer, 1, wx.EXPAND, 0)
        Pin_61_Sizer.Add(self.Pin_61_Enable, 0, 0, 0)
        Pin_61_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_61_Sizer.Add(Pin_61_Status_Label, 0, wx.ALL, 1)
        Pin_61_Sizer.Add(self.Pin_61_Status, 0, wx.ALL, 2)
        Pin_61_Sizer.Add(self.Pin_61_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_61_Sizer, 1, wx.EXPAND, 0)
        Pin_62_Sizer.Add(self.Pin_62_Enable, 0, 0, 0)
        Pin_62_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_62_Sizer.Add(Pin_62_Status_Label, 0, wx.ALL, 1)
        Pin_62_Sizer.Add(self.Pin_62_Status, 0, wx.ALL, 2)
        Pin_62_Sizer.Add(self.Pin_62_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_62_Sizer, 1, wx.EXPAND, 0)
        Pin_63_Sizer.Add(self.Pin_63_Enable, 0, 0, 0)
        Pin_63_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_63_Sizer.Add(Pin_63_Status_Label, 0, wx.ALL, 1)
        Pin_63_Sizer.Add(self.Pin_63_Status, 0, wx.ALL, 2)
        Pin_63_Sizer.Add(self.Pin_63_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_63_Sizer, 1, wx.EXPAND, 0)
        Pin_64_Sizer.Add(self.Pin_64_Enable, 0, 0, 0)
        Pin_64_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_64_Sizer.Add(Pin_64_Status_Label, 0, wx.ALL, 1)
        Pin_64_Sizer.Add(self.Pin_64_Status, 0, wx.ALL, 2)
        Pin_64_Sizer.Add(self.Pin_64_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_64_Sizer, 1, wx.EXPAND, 0)
        Pin_65_Sizer.Add(self.Pin_65_Enable, 0, 0, 0)
        Pin_65_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_65_Sizer.Add(Pin_65_Status_Label, 0, wx.ALL, 1)
        Pin_65_Sizer.Add(self.Pin_65_Status, 0, wx.ALL, 2)
        Pin_65_Sizer.Add(self.Pin_65_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_65_Sizer, 1, wx.EXPAND, 0)
        Pin_66_Sizer.Add(self.Pin_66_Enable, 0, 0, 0)
        Pin_66_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_66_Sizer.Add(Pin_66_Status_Label, 0, wx.ALL, 1)
        Pin_66_Sizer.Add(self.Pin_66_Status, 0, wx.ALL, 2)
        Pin_66_Sizer.Add(self.Pin_66_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_66_Sizer, 1, wx.EXPAND, 0)
        Pin_67_Sizer.Add(self.Pin_67_Enable, 0, 0, 0)
        Pin_67_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_67_Sizer.Add(Pin_67_Status_Label, 0, wx.ALL, 1)
        Pin_67_Sizer.Add(self.Pin_67_Status, 0, wx.ALL, 2)
        Pin_67_Sizer.Add(self.Pin_67_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_67_Sizer, 1, wx.EXPAND, 0)
        Pin_68_Sizer.Add(self.Pin_68_Enable, 0, 0, 0)
        Pin_68_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_68_Sizer.Add(Pin_68_Status_Label, 0, wx.ALL, 1)
        Pin_68_Sizer.Add(self.Pin_68_Status, 0, wx.ALL, 2)
        Pin_68_Sizer.Add(self.Pin_68_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_68_Sizer, 1, wx.EXPAND, 0)
        Pin_69_Sizer.Add(self.Pin_69_Enable, 0, 0, 0)
        Pin_69_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_69_Sizer.Add(Pin_69_Status_Label, 0, wx.ALL, 1)
        Pin_69_Sizer.Add(self.Pin_69_Status, 0, wx.ALL, 2)
        Pin_69_Sizer.Add(self.Pin_69_Mode_Box, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        Analog_Pin_Grid.Add(Pin_69_Sizer, 1, wx.EXPAND, 0)
        Analog_Pin_Grid.Add((0, 0), 0, 0, 0)
        Analog_Input_Pins_Sizer.Add(Analog_Pin_Grid, 1, wx.EXPAND, 0)
        All_Pin_Sizer.Add(Analog_Input_Pins_Sizer, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 1)
        PWM_Output_Pin_Label = wx.StaticText(self, wx.ID_ANY, "PWM Output Pins")
        PWM_Output_Pins.Add(PWM_Output_Pin_Label, 0, 0, 0)
        Pin_2_Sizer.Add(self.Pin_2_Enable, 0, 0, 0)
        Pin_2_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_2_Sizer.Add(Pin_2_Status_Label, 0, wx.ALL, 1)
        Pin_2_Sizer.Add(self.Pin_2_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_2_Sizer, 1, wx.EXPAND, 0)
        Pin_3_Sizer.Add(self.Pin_3_Enable, 0, 0, 0)
        Pin_3_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_3_Sizer.Add(Pin_3_Status_Label, 0, wx.ALL, 1)
        Pin_3_Sizer.Add(self.Pin_3_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_3_Sizer, 1, wx.EXPAND, 0)
        Pin_4_Sizer.Add(self.Pin_4_Enable, 0, 0, 0)
        Pin_4_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_4_Sizer.Add(Pin_4_Status_Label, 0, wx.ALL, 1)
        Pin_4_Sizer.Add(self.Pin_4_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_4_Sizer, 1, wx.EXPAND, 0)
        Pin_5_Sizer.Add(self.Pin_5_Enable, 0, 0, 0)
        Pin_5_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_5_Sizer.Add(Pin_5_Status_Label, 0, wx.ALL, 1)
        Pin_5_Sizer.Add(self.Pin_5_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_5_Sizer, 1, wx.EXPAND, 0)
        Pin_6_Sizer.Add(self.Pin_6_Enable, 0, 0, 0)
        Pin_6_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_6_Sizer.Add(Pin_6_Status_Label, 0, wx.ALL, 1)
        Pin_6_Sizer.Add(self.Pin_6_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_6_Sizer, 1, wx.EXPAND, 0)
        Pin_7_Sizer.Add(self.Pin_7_Enable, 0, 0, 0)
        Pin_7_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_7_Sizer.Add(Pin_7_Status_Label, 0, wx.ALL, 1)
        Pin_7_Sizer.Add(self.Pin_7_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_7_Sizer, 1, wx.EXPAND, 0)
        Pin_8_Sizer.Add(self.Pin_8_Enable, 0, 0, 0)
        Pin_8_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_8_Sizer.Add(Pin_8_Status_Label, 0, wx.ALL, 1)
        Pin_8_Sizer.Add(self.Pin_8_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_8_Sizer, 1, wx.EXPAND, 0)
        Pin_9_Sizer.Add(self.Pin_9_Enable, 0, 0, 0)
        Pin_9_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_9_Sizer.Add(Pin_9_Status_Label, 0, wx.ALL, 1)
        Pin_9_Sizer.Add(self.Pin_9_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_9_Sizer, 1, wx.EXPAND, 0)
        Pin_10_Sizer.Add(self.Pin_10_Enable, 0, 0, 0)
        Pin_10_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_10_Sizer.Add(Pin_10_Status_Label, 0, wx.ALL, 1)
        Pin_10_Sizer.Add(self.Pin_10_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_10_Sizer, 1, wx.EXPAND, 0)
        Pin_11_Sizer.Add(self.Pin_11_Enable, 0, 0, 0)
        Pin_11_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_11_Sizer.Add(Pin_11_Status_Label, 0, wx.ALL, 1)
        Pin_11_Sizer.Add(self.Pin_11_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_11_Sizer, 1, wx.EXPAND, 0)
        Pin_12_Sizer.Add(self.Pin_12_Enable, 0, 0, 0)
        Pin_12_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_12_Sizer.Add(Pin_12_Status_Label, 0, wx.ALL, 1)
        Pin_12_Sizer.Add(self.Pin_12_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_12_Sizer, 1, wx.EXPAND, 0)
        Pin_13_Sizer.Add(self.Pin_13_Enable, 0, 0, 0)
        Pin_13_Status_Label = wx.StaticText(self, wx.ID_ANY, "Status")
        Pin_13_Sizer.Add(Pin_13_Status_Label, 0, wx.ALL, 1)
        Pin_13_Sizer.Add(self.Pin_13_Status, 0, wx.ALL, 2)
        PWM_Output_Pin_Grid.Add(Pin_13_Sizer, 1, wx.EXPAND, 0)
        PWM_Output_Pins.Add(PWM_Output_Pin_Grid, 1, wx.EXPAND, 0)
        All_Pin_Sizer.Add(PWM_Output_Pins, 1, wx.EXPAND, 0)
        Main_Sizer.Add(All_Pin_Sizer, 3, wx.EXPAND, 0)
        Output_Time_Label = wx.StaticText(self, wx.ID_ANY, "Time Between Output:\n")
        Actuator_Button.Add(Output_Time_Label, 0, 0, 0)
        Buttons.Add(self.Connection_Time_Display, 0, 0, 0)
        Buttons.Add(self.Configure_Pin_In_Out, 0, 0, 0)
        Buttons.Add(self.Update_Output, 0, 0, 0)
        Buttons.Add(self.Configure_Output_Time, 0, 0, 0)
        Buttons.Add(self.Reset_Pin_Button, 0, 0, 0)
        Buttons.Add(self.Full_Reset_Button, 0, 0, 0)
        Actuator_Button.Add(Buttons, 1, wx.EXPAND, 0)
        Button_Sizer.Add(Actuator_Button, 1, wx.EXPAND, 0)
        Button_Sizer.Add((0, 0), 0, 0, 0)
        Main_Sizer.Add(Button_Sizer, 1, wx.EXPAND, 0)
        self.SetSizer(Main_Sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

    def __attach_events(self):

        #Attach events to each pin status:
        for i in range(22, 54):
            eval("self.Pin_{}_Enable.Bind(wx.EVT_CHECKBOX, self.getOnCheck({}))".format(i,i))
        for i in range(2, 14):
            eval("self.Pin_{}_Enable.Bind(wx.EVT_CHECKBOX, self.getOnCheck({}))".format(i,i))
        for i in range(54, 70):
            eval("self.Pin_{}_Enable.Bind(wx.EVT_CHECKBOX, self.getOnCheck('{}'))".format(i,i))


        self.Configure_Pin_In_Out.Bind(wx.EVT_BUTTON, self.ConfigurePinIO)
        self.Update_Output.Bind(wx.EVT_BUTTON, self.UpdatePinOutput)
        self.Configure_Output_Time.Bind(wx.EVT_BUTTON, self.ConfigOutputTime)
        self.Reset_Pin_Button.Bind(wx.EVT_BUTTON, self.ResetPins)
        self.Full_Reset_Button.Bind(wx.EVT_BUTTON, self.FullReset)
        self.Start_Connection_Button.Bind(wx.EVT_BUTTON, self.StartSerialComms)
        self.Stop_Connection_Button.Bind(wx.EVT_BUTTON, self.StopSerialComms)
        self.Show_Serial_Monitor.Bind(wx.EVT_BUTTON, self.StartSerialMonitor)

        self.Bind(wx.EVT_CLOSE, self.OnClose)
    # end of class Pin_Control

    def getOnCheck(self, arg):
        def PinChange(event):
            if(event.IsChecked()):
                print("adding pin {}".format(arg))
                #If the checkbox was checked, add pin.
                #sel = self.Pin_22_Mode_Box.GetSelection()
                if int(arg)<22:
                    sel = 1
                else:
                    sel = eval("self.Pin_{}_Mode_Box.GetSelection()".format(arg)) 
                if sel==0:
                    self.SerialLine.PinsList.addPin(arg,0)
                    print("Added pin {} as input".format(arg))
                else:
                    self.SerialLine.PinsList.addPin(arg,1)
                    print("Added pin {} as output".format(arg))
            else:
                print("removing pin {}".format(arg))
                if not self.SerialLine.PinsList.removePin(arg):
                    print("Error removing pin.")
        return PinChange
        
    def ConfigurePinIO(self, events):
        print("Configure pin IO")
        self.SerialLine.InitializePins()
    
    def UpdatePinOutput(self, events):
        print("Updating pin output values")
        #TODO: Comb through all pins, update their values.
        for x in self.SerialLine.PinsList.PinList:
            if x.mode==1:
                x.value = float(eval('self.Pin_{}_Status.GetValue()'.format(x.pin)))
        self.SerialLine.ChangeOutputPinValue()

    def ConfigOutputTime(self, events):
        print("Configuring output time")
        self.SerialLine.startOutputTime(int(self.Connection_Time_Display.GetValue()))

    def ResetPins(self, events):
        #Remove all pins from list, and clear all their stored values.
        for x in range(22, 70):
            exec("self.Pin_{}_Enable.SetValue(False)".format(x))
            exec("self.Pin_{}_Mode_Box.SetSelection(-1)".format(x))
            exec("self.Pin_{}_Status.SetValue(\"\")".format(x))
        for x in range(2, 14):
            exec("self.Pin_{}_Enable.SetValue(False)".format(x))
            exec("self.Pin_{}_Status.SetValue(\"\")".format(x))
        
        print("Performing pin reset")
        self.SerialLine.resetPins()

    def FullReset(self, events):
        #Perform a full reset on all pins.
        print("Performing full reset, clearing pins list and resetting elegoo.")

    def StartSerialComms(self, events):
        #Get the values for the COM port
        #And the Baud rate, pass to initiateConnection:
        if self.SerialLine.initiateConnection(int(self.Baud_Rate_Combo_Box.GetValue()), self.ports[self.PortComboBox.GetSelection()]):
            self.Stop_Connection_Button.Enable(True)
            self.Start_Connection_Button.Enable(False)
            #TODO: Have the bottom serial ctrl buttons disabled
            #Enable them when necessary.
            

    def StopSerialComms(self, events):
        print("Stopping Serial Thread")
        if self.SerialLine.stopConnection():
            self.Stop_Connection_Button.Enable(False)
            self.Start_Connection_Button.Enable(True)


    def UpdateUI_Inputs(self):
        #Redraw all status based on inputs from PinsList
        #This only updates based on inputs.
        for x in self.SerialLine.PinsList.PinList:
            if x.mode==0:
                #For each input, change the status box.
                #self.Pin_22_Status.SetValue(x.value)
                #print("Updating {} on UI".format(x.pin_number))
                exec("self.Pin_{}_Status.SetValue(str(x.value))".format(x.pin))
                #TODO: Test this.        

    def startUIThread(self):
        self.thread = threading.Thread(target=self.UpdateUIThread)
        self.thread.setDaemon(True)
        self.thread.daemon = True
        self.alive.set()
        self.thread.start()
        print("Started UI Thread.")
        
    def stopUIThread(self):
        if self.thread is not None:
            print("Stopping thread.")
            self.alive.clear()
            time.sleep(0.5)
            self.thread.join()
            self.thread = None
            print("Thread stopped")

    def closeSelf(self):
        self.stopUIThread()
        self.Destroy()

    def OnClose(self, event):
        self.Show(False)

    def UpdateUIThread(self):
        while self.alive.isSet():
            time.sleep(0.25)
            if self.SerialLine.UI_Update_Flag:
                self.SerialLine.UI_Update_Flag=False
                self.UpdateUI_Inputs()
            if self.SerialMonitor!=None:
                #TODO: Update the text box with text from serial comm
                if self.SerialLine.SerialCommListUpdated:
                    self.SerialLine.SerialCommListUpdated = False
                    self.SerialMonitor.TextView.AppendText(self.SerialLine.SerialCommList[len(self.SerialLine.SerialCommList)-1])
                    self.SerialMonitor.TextView.AppendText("\n")
            if self.SerialLine.alive.isSet():
                self.Connection_Status_Display.ChangeValue("Connected")
            else:
                try:
                    #For some reason this part is causing the issue.
                    if self.alive.isSet():  
                        self.Connection_Status_Display.ChangeValue("Disconnected")
                except:
                    print("couldn't change last value thats fine tho.")

        print("done executing.")


    def StartSerialMonitor(self, events):
        self.SerialMonitor.Show()
        self.SerialMonitor.active = True

    def externalResetPins(self):
        #22-69
        self.ResetPins(None)


#'''
#External AddPin - 
#Method to add a pin to the PinsList,
#Change the status of the Pin Manager (Tick the checkbox to activate pin, change the pin mode as necessary, etc.)

#Type 0 - Output
#Type 1 - Input

    def externalAddPin(self, pin, pintype, input=0):
        exec("self.Pin_{}_Enable.SetValue(True)".format(pin))
        #Make sure the proper box exists for this first.
        if (pin>21):
            exec("self.Pin_{}_Mode_Box.SetSelection(pintype)".format(pin))
        exec("self.Pin_{}_Status.SetValue(str(input))".format(pin))
        #self.Pin_24_Enable.SetValue(self, True)
        if pintype==0:
            self.SerialLine.PinsList.addPin(pin, 0, input)
        else:
            self.SerialLine.PinsList.addPin(pin, 1, input)
        print("External pin {} added as {}".format(pin, pintype))
        
#
#ExternalRemovePin - 
#See ExternalAddPin above.
#

    def ExternalRemovePin(self, pin):
        eval("self.Pin_{}_Enable.SetValue(False)".format(pin))
        self.SerialLine.PinsList.removePin(pin)

#
#ExternalChangePinStatus - 
#See the External AddPin description above.

    def ExternalChangePinStatus(self, pin, status):
        
        exec('self.Pin_{}_Status.SetValue(\"{}\")'.format(pin, status))

    #ExternalStartSerial - start the serial comms port from outside.  Update UI Accordingly.
    def ExternalStartSerial(self, port_num, rate=9600):
        self.PortComboBox.SetSelection(port_num)
        self.StartSerialComms(None)

    #ExternalStopSerial - stop the serial comms port from outside class.  Update UI accordingly.
    def ExternalStopSerial(self):
        self.StopSerialComms(None)

#getPinValue - easier method
#to get and return a specific pin value.

    def getPinValue(self, pin):
        return self.SerialLine.PinsList.getPinValue(pin)

    def getSerialActive(self):
        return self.SerialLine.getSerialActive()


class MyApp(wx.App):
    def OnInit(self):
        self.Main_Window = Pin_Control(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Main_Window)
        self.Main_Window.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
