#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Fri Jan  8 14:29:21 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Serial_Monitor(wx.Frame):

    def OnClose(self, event):
        self.Show(False)

    def __init__(self, *args, **kwds):
        # begin wxGlade: Serial_Monitor.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.TextView = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.__set_properties()
        self.__do_layout()

        self.active = False
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Serial_Monitor.__set_properties
        self.SetTitle("Serial Monitor")
        self.TextView.SetMinSize((360, 260))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Serial_Monitor.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.TextView, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade



# end of class Serial_Monitor

class MyApp(wx.App):
    def OnInit(self):
        self.Serial_Monitor = Serial_Monitor(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Serial_Monitor)
        self.Serial_Monitor.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
